src/component/utils/ScrollTopButton.js

수지킴님이 말씀하신, 이용 안내 페이지 footer에 화면이 다다르더라도 버튼이 사라지지 않도록 구현합니다.
**issue #130** 을 해결했습니다. 이제 footer에 도달하더라도 버튼이 사라지지 않습니다. 그 과정에서 window객체와 특정 요소의 크기를 계속해서 업데이트하기 때문에, 수평 반응형도 자동으로 이루어집니다.
```js
if (
window.scrollY > activeScrollY / 2 &&
window.scrollY < inActiveScrollY
) {
setActive(true);
} else if (window.scrollY >= inActiveScrollY) {
setFooterShownHeightRem(
window.scrollY +
window.innerHeight -
(document.body.scrollHeight -
document.getElementsByClassName("footer")[0].scrollHeight),
);
} else {
setActive(false);
}
```
여기서 inActiveScrollY에 scrollY가 도달한다면 기존에는 inActive가 되었습니다. 여기서 inActive을 시키지 않고 footer가 나타날 때의 버튼의 위치에서 멈춰있도록 만들었습니다. footerShownHeightRem 이 화면에 footer가 보이는 만큼의 px을 나타냅니다.
- 기본 예시
https://user-images.githubusercontent.com/79993356/166447658-307ea5b9-522d-4403-8651-e6fe3c855c4 …

FEATURE: footer에서도 ScrollTopButton 유지

---

src/component/search/Search.js

- 검색어가 없을시 전체 도서 목록을 반환하므로, Subtitle을 `전체 도서 목록` 으로 표시
<br>
- 이전에는 page가 바뀌어도 pageRange가 바뀌지 않는 경우가 생겨 수정했습니다
<br>

JIP-190 FIX: SubTitle 케이스 추가, 검색 시 pageRange 초기화

---

src/component/book/BookDetail.js
src/component/book/BookStatus.js
src/component/reservation/Reservation.js
src/component/reservation/UserConfirm.js
src/css/BookDetail.css
src/css/BookStatus.css
src/css/MidModal.css

- 요청보내는 주소와 바디에 실어보내는 파라미터를 변경하였습니다.
- 예약을 bookId가 아니라 bookInfoId에 겁니다.
- 예약을 bookId가 아니라 bookInfoId에 걸게 됨에 따라 상세페이지 `예약하기` 및 `예약불가` 버튼의 위치를 변경하였습니다.
- 버튼의 위치가 변경되면서 공간이 확보되어 모바일 화면의 도서 상태목록도 pc 화면과 동일하게 보입니다.

Jip 195 도서 상세페이지에서의 예약 수정

---

src/component/mypage/EditEmail.js
src/component/mypage/EditPassword.js
src/component/mypage/Mypage.js
src/component/mypage/MypageRentedBook.js
src/component/mypage/MypageReservedBook.js
src/component/reservedloan/ReservedFilter.js
src/component/reservedloan/ReservedLoan.js
src/component/reservedloan/ReservedModalContents.js
src/component/reservedloan/ReservedTableList.js
src/component/utils/HeaderModal.js
src/css/EditEmail.css
src/css/EditPassword.css
src/css/Mypage.css
src/css/MypageRoutes.css
src/css/ReservedLoan.css
src/css/reset.css

1. 비밀번호 network-payload 에서 안 보이는 방법이 없을까요? ► 멘토링 해야할 듯!
2. 비밀번호 조건이 보이도록 추가합니다.
3. 모바일에서 인콰이어 박스를 줄입니다.
4. width 가 780px인 임계값을 고려합니다.
5. min-width 360px 추가
6. 마이페이지 이메일 및 패스워드 모바일 반응형 
1. 왜 예약이 종료가 되었는지 적어주어야 합니다.
2. 예약 취소를 기본적으로 빨간색으로 만들어줍니다.
3. wrapper에 min-width 360px 을 추가합니다.
- 마이페이지 patch 요청에서 params를 빼서 보내줍니다.
- 예약페이지 prop이 없었던 것들을 추가했습니다.
- 모바일 헤더에 마이페이지 연결했습니다.
<p>
</p>
예약 만료 이유에 대해서는 
- status 1 : 대출완료
- status 2 : 예약 취소
- status 3 : 예약 기한 만료
입니다!
<p>
</p>

Jip 224 마이페이지 및 예약 대출 css 수정

---

src/component/search/CategoryFilter.js
src/component/search/Search.js

- 카테고리 필터의 Next Category 버튼과 Pre Category 버튼이 제대로 작동하지 않아 수정했습니다
- 원인은 `categoriesScrollX` 가 소수점이 될때가 있어서 조건문이 의도대로 작동하지 않은 탓이었습니다.
- 보정값(EPSILON)을 추가하여 해결했습니다.
<br>
- errorCode와 MiniModal을 초기화하여 에러상황과 구분했습니다

Jip 234 category filter 의 next 및 pre 버튼 작동 fix

---

src/component/userManagement/UserUsageInfo.js

- 변수명 수정: `dueDate` -> `duedate`
- 타입 수정: duedate가 Date 타입에서 string으로 바뀜에 따라 사용방법을 바꿨습니다.

JIP-238 FIX: duedate 변수명 및 타입 일치

---

src/component/mypage/EditEmail.js
src/component/mypage/EditPassword.js
src/component/mypage/Mypage.js
src/component/mypage/MypageRentedBook.js
src/component/mypage/MypageReservedBook.js
src/css/EditEmail.css

이메일 변경 페이지에서 자신의 것이 아닌 이상한 것이 들어있는 오류가 발생했습니다.
nickname을 nicknameOrEmail로 변경하지 않아서 생긴 오류였으며 이를 수정했습니다.
예약 취소 완료를 나타내는 모달과, 박스의 타이틀의 전후관계가 이상합니다.
1) 기존 예약정보 타이틀과 예약 취소의 전후 관계가 이상한 것을 해결했습니다. 
기존에는 Reserve에서 따로 모달을 썼기 때문에, 해당 모달이 예약정보 타이틀보다 하위 컴포넌트이기 때문에 z-index가 먹히지 않는 오류였습니다. 따라서 하위 컴포넌트의 모달을 지우고, 상위 컴포넌트에서 상태값을 상속해주면서 이를 해결했습니다.
2) 얘약 취소를 하면, 자동으로 전체 마이페이지 정보를 다시 불러오도록  했습니다. 
get 부분을 따로 함수로 만들어 해당 함수가 모달이 닫힐 때에 실행됩니다.
3) 이메일 변경 페이지에서, 이메일을 전부 중앙정렬로 만들었습니다.
4) 이메일과 패스워드를 변경하면 모달이 안 뜨고 바로 이전 페이지로 넘어갑니다.
이는 모달이 뜨기 전에 `history.goback`을 해서 그렇습니다. 이를 모달을 닫아야만 실행되도록 교체했습니다.
5) `eslint` 오류를 임시로 주석처리한 것들을 이제 모두 교체합니다.

Jip 239 마이페이지 버그 수정

---

src/component/mypage/Mypage.js

기존에는 query.errorCode 를 통해 상태값을 설정하고 있었습니다.
그런데 모달을 닫더라도 쿼리 스트링이 삭제되지 않았습니다.
따라서 useHistory를 사용해 쿼리 스트링을 삭제합니다.

JIP-246 FIX: 마이페이지 에러 모달을 닫을 때에 쿼리 삭제

---

src/css/Header.css

Header.css 에서 `.gnb__user__button` 과 `.gnb__button` 의 위치를 변경하여 해결했습니다.
`all: unset` 설정이 중간에 적용되었던것이 원인이라 추측 중입니다.
추가로 유저 토글 버튼의 아이디가 특정 width(10rem)을 벗어날 경우 `...` 처리 했습니다.

JIP-282 FIX: 빌드시 gnb__user__button css 적용안되는 문제 해결

---

src/css/Login.css
src/css/Register.css

1. register, login 컴포넌트를 정중앙에 위치하게끔 설정
- 현재
- 수정후 
2. register에서 패스워드 오류시 폰트 사이즈 조절
- 현재
- 수정후

JIP-283 login register 간단 css 수정

---

src/component/userManagement/UserDetailInfo.js

유저정보를 수정할 때 빈칸으로 둔 채 저장하면 null 값으로 업데이트 되도록했습니다.
다만 인트라 id, 인트라 닉네임, 슬랙 id 일부만 null 상황이 괜찮을지는 좀 더 고민해봐야할 것 같습니다..!
그리고 다른 항목은 null로 업데이트가 되는데 인트라 id는 null을 보내면 백엔드 쪽에서 먹히지 않고 있는거 같네요.
https://user-images.githubusercontent.com/74581396/177002488-618106f3-ab68-40ff-ad51-508a8b2e09fb.mov

Jip 270 debug 유저 정보 초기화 처리

---

src/component/utils/MobileHeader.js
src/css/HeaderModal.css
src/css/MobileHeader.css

최소화면보다 작아질경우 헤더 모달의 위치가 바뀌는 오류를 수정했습니다.
https://user-images.githubusercontent.com/74581396/177036451-d8a0bf5d-0c31-49e6-916f-d6606deb3fea.mov

Jip 288 화면이 360 px 보다 작을 때 모바일 헤더 모달 위치 오류

---

src/component/mypage/EditEmail.js
src/component/mypage/EditPassword.js
src/component/mypage/Mypage.js
src/component/mypage/MypageReservedBook.js
src/css/Mypage.css

**로그인하지 않은 유저는 바로 홈으로 돌아가게 만들었습니다.** 
사실 로그인하지 않은 유저가 mypage로 올 수 있는 방법이 직접 주소창에 치는 수밖에 없습니다. 
다만 마이페이지를 켜둔채로 토큰이 만료되거나 하는 상황을 대비해서, 로그인 페이지로 넘어가게 만들었습니다.
유저 정보 및 대출 책 정보, 예약 책 정보에서도 모두 새로운 줄로 넘어가게 됩니다.
FileChanges 에서 더욱 확실하게 보실 수 있어요!

Jip 300 마이페이지 qa 1 차 수정

---

src/css/HeaderModal.css
src/css/MobileHeader.css
src/css/Search.css
src/css/WishBook.css

- height를 `100vh` 로 설정했지만 갤럭시 폴드와 같이 너비가 좁고 높이가 높은 경우, 최소너비(360px)에서 비율이 줄어드는 방식이기 때문에 화면을 꽉채우지 못하는 오류가 있어 `100vh` 대신 `1000vh` 를 사용하였습니다.
<br>
- 수정 전
<br>
- 수정 후

JIP-317 FIX: 헤더 모달 background height 더 높게 변경

---

src/component/reservedloan/ReservedModal.js
src/component/reservedloan/ReservedModalContents.js

예약 취소를 누르면 뜬끔없이 대출이 완료되었다는 문구가 떴었는데 이를 수정했습니다.
bookId 를 부여받지 못한 도서는 callsign 숨깁니다. 예약 만료일 대신 예약 시작일을 보여줍니다.
다만 현재 reservation/search 로 받아오는 데이터에 문제가 있는 상황입니다. 프론트 컴포넌트에서는 이 데이터를 그대로 보여주고 있는데, 연체일이 제대로 나오고 있지 않습니다. 이는 추후에 서버개발자와 논의해야 합니다.

Jip 305 예약 대출 페이지 qa 1 차 수정

---

src/component/userManagement/UserBriefInfo.js
src/component/userManagement/UserDetailInfo.js
src/component/userManagement/UserManagement.js

- 모달에서 유저 정보 수정 시 새로고침을 하지 않아도 유저 정보 목록을 보여주는 페이지에 바로 반영 되도록 수정했습니다.
https://user-images.githubusercontent.com/74581396/177955520-a8f566ec-f28d-425d-8386-3fdc50f96589.mov

JIP-329 REFACT: 유저 정보 수정할 시 BriefInfo 에 바로 반영

---

src/component/reservedloan/ReservedLoan.js
src/component/return/ReturnBook.js

예약대출, 반납 페이지에서 검색어를 변경했음에도 불구하고, 검색할 페이지는 이전 값으로 설정되어 있는 오류가 있었습니다.
검색어와 연결된 useEffect를 설정해서 검색어 변경시 Page를 1로 설정해주고, 검색을 실행하게끔 했습니다.
https://user-images.githubusercontent.com/48037775/178101561-1ababd39-5614-4c2c-b84d-1f7a129faab6.mov
https://user-images.githubusercontent.com/48037775/178101608-95117371-ff48-497a-b371-cc959d10ef10.mov

JIP-327 FIX: 예약대출, 반납 페이지 검색어 변경시 Page 1로 초기화

---

src/component/main/MainNew.js
src/component/main/MainNewBook.js
src/component/main/MainNewBookList.js
src/css/MainNew.css

모바일 화면에서 메인페이지의 신작도서 이미지가 작아지도록 변경하였습니다
이미지가 없는 경우 회색 이미지로 대체됩니다
- css 대신 js 파일에서 width 설정하도록 변경했습니다
- window.innerWidth를 감지해서 모바일 화면일때 width를 줄여줍니다.
- js 컴포넌트마다 역할을 분명히 했습니다 
- mainNew : api 호출 및 데이터 저장
- mainNewBookList : 버튼 및 이벤트 동작 설정
- mainNewBook : 책 노출 방식 결정 이미지가 없는 경우 회색 면으로 대체

JIP-313 메인 신작도서 이미지 조절 및 깨진 이미지 대체

---

src/component/book/BookDetail.js
src/component/main/MainPopularCenter.js
src/component/search/BookInfo.js

- bookInfo table의 publishedAt 값이 nullable하게 바뀌면서 timezone 형식으로 예측한 속성에 적용한 함수가 컴파일 오류를 발생했습니다
- publishedAt이 null 일때 발행일자 자체를 보이지 않도록 수정했습니다.
1. 옵셔널체이닝 `?` 추가
- 발행일자: null 로 표기되어 적절하지 않아보입니다.
2. null이면 값 자체를 "-"로 변경
- null이나 -나 큰 차이가 없어보입니다.
3. publishedAt이 없을 때 발행일자 p 태그 자체를 없애버리기
- 현재 진행중인 방식입니다
- 불필요한 html 태그를 남겨놓지 않도록 설정할 수 있습니다. html문서 안의 요소 적절성을 지킬 수 있습니다.
- 애매한 여백이 생깁니다
4. book.publishedAt이 없으면 이미지 크기 및 요소 크기 변경
- css로 해결할 수 없는 문제입니다. js에서 직접 요소의 style에 접근해서 바꿔야 합니다. 추후 수정하고 싶을 때 css 변동만으론 부족합니다
- 상황에 맞는 랜더링을 하기 위해 수많은 상태를 저장해야 합니다.
- 코드가 복잡해지고 처리하기 위한 시간이 많이 필요합니다.
- 펼쳐진 책의 상태에 따라 요소의 크기가 변동하여 푸터의 위치, 스크롤등의 변화가 생깁니다.
- 백엔드에서 임의로 9999-01-01로 변경해서 보내주고 있어서 테스트를 거치지 못했습니다 (7/10 03:55 기준)
- bookinfo DB publishedAt에 연결된 데이터가 null이 가능해지면서 어떤 api가 영향을 받을지 예상되지 않습니다. 최대한 반영을 했으나 컴파일 오류가 …

JIP-335 HOTFIX: 메인 publishedAt null일때 컴파일 에러 해결

---

src/component/userManagement/UserDetailInfo.js

- penaltyEndDate가 null 이거나 오늘 이전인 경우 프론트에서 보이는 penaltyEndDate 기본값을 오늘 -> 빈문자열로 수정했습니다.
https://user-images.githubusercontent.com/74581396/179339826-f97736bd-7332-4b58-81a0-5629e73545be.mov

JIP-346 FIX: 프론트에서 보이는 penaltyEndDate 기본값을 빈문자열로 설정

---

.github/workflows/main.yml

수동으로 생성하던 무효화정책을 github action으로 처리하려 합니다. 
Deploy run 다음 단계 추가          
` aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CDN_DISTRIBUTION_ID }} --paths "/*"`
Name: AWS_CDN_DISTRIBUTION_ID
Value : aws 콘솔에서 확인한 배포 id `E1IS2(이하 생략)` 42library.kr과 연결되어 있음
s3 버킷을 갱신하더라도 CDN 엣지에 남아있는 캐시때문에 변경사항이 최대 24시간까지 반영되지 않을 수 있습니다. 
이 캐시를 지우기 위해 무효화가 필요합니다.
https://docs.aws.amazon.com/ko_kr/AmazonCloudFront/latest/DeveloperGuide/Invalidation.html
https://kiwinam.com/posts/42/remove-cache-cloud-front/
https://hyeon9mak.github.io/cloudfront-caching-control-with-invalidations/

 JIP-352 ENV: aws cloudfront 무효화 생성 자동화

---

.github/workflows/main.yml

지난 캐시 무효화 시도 실패의 문제 해결
- 프론트 배포에 쓰인 사용자의 IAM 권한이 없어 cloudfront 에 접근할 수 없었습니다. 
- 자격증명에 필요한 config 설정이 부족했습니다. github action에 기본 설정이 없기 때문에 region을 생략할 수 없습니다.
- 배포(s3 빌드) 단계와 cloudfront 캐시 무효화 단계를 분리했습니다. 
- aws 자격증명 과정에서 필요한 region 설정을 추가했습니다. 
- aws IAM frontdeploy 권한에 CloudFront에 접근할 수 있는 권한을 추가했습니다. 
- fork 한 레파지토리에서 yml 파일 실행  및 성공 여부를 확인했습니다.

JIP-352 aws cloudfront 무효화 생성 자동화 (재시도)

---

src/component/search/Sort.js

https://github.com/jiphyeonjeon-42/frontend/issues/253#issue-1355233856
정렬기준 안내가 잘못 되어 있는 부분을 발견하여 수정했습니다.

Issue/249/도서 목록 페이지에서 정렬 기준 수정

---

src/App.js
src/LimitedRoute.js
src/component/mypage/Mypage.js

> LimitedRoute 도입으로 가독성을 개선합니다. 
- 라우트 단계에서 전역상태의 user 권한을 확인하는 LimitedRouter 추가
- isAdminOnly / isLoginOnly를 구분해서 라우터 페이지별 권한 명시
- 페이지 내에서 user권한을 확인하고 페이지 이동하는 코드 삭제

Issue/262 라우터 코드 가독성 개선

---

src/component/book/BookDetail.js

> 도서 상세 화면의 문구를 일부 수정합니다 
- 기부자 null일 때 표시 안하도록
- 비치중인 책이 있어 예약 불가능일 때 문구 수정 예약 불가 -> 대출 가능

Issue/267 도서 상세 문구 수정

---

src/component/main/MainPopular.js

> 요약
인기 도서 소개 문구를 수정했습니다.
> 변경사항
> 프리뷰
* Before
* After

issue/264 인기도서 소개 문구 수정

---

src/component/book/BookDetail.js
src/component/book/BookStatus.js
src/css/BookStatus.css

- 도서 상세페이지 기부자 정보 위치 이동
- 개별 책 상태정보 옆에 기부자 표기
- 767px 이하 모바일 화면에서 반납예정일 생략
- 화면보다 기부자 이름이 긴 경우 생략될 수 있음 
Resolves #288

FIX: 도서 기부자 상태정보로 이동

---

src/api/books/useGetBooksId.js

- 바코드 인식했을때 대출이 안되는 오류를 해결했습니다 
- 바코드 인식후 가져오는 book 객체에 bookId 추가

HOTFIX: 바코드로 대출할 때 오류 수정

---

src/App.js
src/api/books/useGetBooksIdForStock.js
src/api/stock/useGetStockSearch.js
src/api/stock/usePatchStockUpdate.js
src/component/bookStock/BookStock.js
src/component/bookStock/BookStockCheckByReadingQR.js
src/component/bookStock/BookStockCheckedList.js
src/component/bookStock/BookStockCheckedListLine.js
src/component/bookStock/BookStockDetailModal.js
src/component/bookStock/BookStockNeedToCheckList.js
src/component/bookStock/BookStockNeedToCheckListLine.js
src/component/utils/BookDetailView.js
src/component/utils/InquireBoxBody.js
src/component/utils/InquireBoxItem.js
src/component/utils/InquireBoxLine.js
src/component/utils/Pagination.js
src/component/utils/SpanWithLabel.js
src/css/BookDetailView.css
src/css/BookStock.css
src/css/BookStockCheckedList.css
src/css/BookStockDetailModal.css
src/css/BookStockNeedToCheckList.css
src/css/InquireBoxBody.css
src/css/InquireBoxItem.css
src/css/InquireBoxLine.css
src/css/SpanWithLabel.css
src/data/tablist.js
src/hook/useDialog.js
src/util/parseBookIdFromQRLabel.js

도서 분실확인용 재고관리 페이지 추가
https://github.com/orgs/jiphyeonjeon-42/discussions/1  에서 논의했던 기능을 페이지로 구현
- 비치되어 있는 책의 라벨 QR 코드 인식
- 라벨 내 bookId 기준 책정보 모달 확인
- 실물 책과 모달창이 일치하면 업데이트 버튼 클릭
- 확인 완료 목록에 추가됨 (새로고침시 사라짐)
- 비치된 책을 모두 확인했는데도 확인 필요 목록에서 남은 책은 분실처리
- QR 리더기로 인식한 책정보 모달
- 업데이트 요청 성공한 책 목록 
- 업데이트되지 않은 목록
- 분실처리

Issue/359 도서 분실확인용 페이지

---

src/component/search/Search.js

제보받은 문제를 해결했습니다.
검색어를 변경하면 카테고리가 초기화됩니다.
검색어 변경에도 이전에 선택한 카테고리가 유지됨
검색어 변경시 url에서 검색어와 페이지만 수정하고 있었음
검색어 변경시 카테고리 및 정렬도 초기화하도록 추가
resolve #348

FIX: 검색 검색어 변경시 url 카테고리 및 정렬 삭제

---

src/component/bookManagement/BookManagementModalToPrint.js

도서관리 라벨출력시 최종 인쇄화면이 제대로 보이지 않는 현상 해결
라벨출력 최종 인쇄시 화면이 깨지는 문제
css 로딩이 끝나기 전에 바로 인쇄가 시작됨
인쇄 요청에 지연 0.5초 추가
resolves #353

FIX: 도서관리 라벨출력 인쇄 타이밍 지연

---

src/component/eLibraryIn42Box/EventPage.jsx

만우절 페이지의 iframe 에서 전자도서관이 제대로 로드되지 않는 문제 해결했습니다. 
- 다른 도메인으로 배포해본 결과 제대로 작동되는 점 확인했습니다. 
https://test.42jip.com/41

HOTFIX: 만우절 페이지 전자도서관 링크 수정

---

.github/workflows/main.yml

git action에 활용되는 workflow의 버전을 최신버전으로 수정했습니다. 
git action이 제대로 진행되지 않던 문제 
- 우분투 버전 18.04를 더이상 지원하지 않았음
https://github.com/actions/runner-images/issues/6002
- 18.04 -> latest으로 변경, 최신으로 항상 유지되도록 수정함
- 기타 checkout과 cache action도 최신 버전 (v3)으로 변경함
https://github.com/actions/checkout
https://github.com/actions/cache
- 레포지토리 fork 후 action이 제대로 돌아가는 점 확인했습니다 (deploy는 aws 설정 미적용으로 실패지만 직전까지는 진행됩니다)
- checkout/ cache 버전도 변경 후 관련 오류가 없어지는 점 확인했습니다.

ENV: git action workflow 버전 업데이트

---

src/LimitedRoute.jsx
src/api/auth/usePostAuthLogin.js
src/component/login/Auth.jsx
src/component/login/Logout.jsx

로그인 등 권한 확인후 리다이렉트시 히스토리 기록을 남기지 않도록 수정합니다. 
모바일 환경에서는 뒤로가기를 연속으로 하면 브라우저 창이 닫아져야 함
집현전 홈페이지는 뒤로가기로 창닫기가 제대로 작동하지 않던 문제
로그인 페이지를 거친 후 남은 히스토리 내역 + 이미 로그인된 상태에서 다시 로그인 접근시 메인으로 리다이렉트 = 뒤로가기 감옥
로그인 관련 리다이렉트 시 히스토리 스택에서 제외
- 최초 도달시의 기록이 하나 남아서 1회 한정 뒤로가기에 영향을 받지 않습니다.
364

fix: 로그인 관련 리다이렉트 시 히스토리 스택에서 제외

---

src/component/addbook/AddBook.jsx
src/component/bookManagement/BookManagement.jsx
src/component/bookStock/BookStock.jsx
src/component/reviewManagement/ReviewManagement.jsx
src/component/userManagement/UserManagement.jsx
src/data/headerMenu.js
src/data/tablist.js

DB 관리 페이지에 과도하게 몰린 탭을 분산시킵니다.
대출/반납 > 대출, 예약대출, 반납, 전체기록
DB 관리 > 유저관리, 도서등록, 도서관리, 리뷰관리, 재고관리
- 태그 관리가 추가될 경우 6~7개가 되어야 함 
- 5개인 현재도 너무 복잡함
대출/반납 > 대출, 예약대출, 반납, 전체기록
유저관리
도서관리 > 도서등록, 도서관리, 재고관리
추가기능관리 > 리뷰관리, 도서별태그(추가예정), 태그머지(추가예정)
현재 초안은 태그기능 UI 논의과정에서 정리된 내용을 바탕으로 하고 있습니다. 
구현 후 확인해보니 탭 대신 헤더 메뉴가 복잡해진 느낌이 듭니다
메뉴구성 관련 다른 의견이 있으시면 편하게 말씀주세요!

refactor: DB관리 탭 분리

---

tsconfig.json
tsconfig.vite.json

- closes #382 
타입스크립트 마이그레이션을 위한 설정 파일입니다.
#404 에서 `tsconfig.json`과 `tsconfig.vite.json`에 대한 자세한 설명을 확인하실수 있습니다.
#405 를 참고해주세요.

build: 타입스크립트 설정

---

package.json

- fixes #413
- 사용하지 않던 `qs` 패키지를 제거했습니다.
- [react](https://www.npmjs.com/package/@types/react), [react-dom](https://www.npmjs.com/package/@types/react-dom) 라이브러리는 [flow](https://flow.org)로 작성되었기 때문에 별개의 패키지로 타입스크립트 타입을 제공하고 있습니다. 해당 타입 패키지를 추가했습니다.

build: @types 패키지 추가

---

src/component/utils/SearchBar.tsx

- fixes #428 
도서 검색시 [encodeURIComponent](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent)을 사용해 특수문자를 인코딩합니다. 
인코딩시 URI: `http://localhost:4242/search?search=c%2B%2B&page=1`

fix: 도서검색시 특수문자 인코딩

---

src/component/main/MainNewBook.tsx
src/component/utils/Image.tsx

- fixes #435 
| 이전 | 이후 |
|--------|--------|
| ![전][전] | ![후][후] |
[전]: https://github.com/jiphyeonjeon-42/frontend/assets/54838975/c678b9fd-5db5-4a93-b9c6-fc68aa39a307
[후]: https://github.com/jiphyeonjeon-42/frontend/assets/54838975/2c45f80e-b2d7-463e-a7c4-e093622398ee
- `Image` 컴포넌트의 `width`, `height` 타입을 엄격하게 변경했습니다 (숫자와 `${숫자}px`만 허용)
- `MainNewBook`의 크기 속성을 문자열에서 숫자로 변경했습니다

fix: 메인 페이지 이미지가 지나치게 큼

---

src/component/utils/BarcodeReader.tsx

deviceId 속성이 undefined로 페이지가 터지는 문제 해결
99877cd568eca9ba2ef5c968a5534c6f214cdd69 커밋에서 빠진 옵셔널체이닝 다시 추가
- fixes #466

fix: 바코드리더 deviceId undefined 오류 해결

---

src/component/rent/RentConfirm.tsx

대출이 가능한 상태라서 버튼 색이 변했는데도 눌리지 않던 문제 해결
- fixes #485
- 대출하기 버튼 색변경과 disabled 로직 통일

fix: 도서와 유저 선택후 대출하기 버튼이 눌리지 않는 문제 해결

---

src/component/main/MainPopularCenter.tsx

- fixes #493 
dc85592d97dbdd1a03dfe5721bcb30c1b7363b43 에서 삭제되었던 id 값 되살렸습니다

fix: 메인 인기도서 button id 다시 추가

---

src/asset/css/BookDetail.css
src/component/book/BookDetail.tsx

책정보를 불러올 수 없는 상황에도 기본 UI 유지하도록 수정
- fixes #509
| |이미지|
|---|---|
|before|![image](https://github.com/jiphyeonjeon-42/frontend/assets/74622889/731a4efb-a8ce-479d-b541-6a18f1eef0e2)|
|after|<img width="1615" alt="image" src="https://github.com/jiphyeonjeon-42/frontend/assets/74622889/800040dd-c758-4005-99d5-f22b41513a99">|

fix:상세페이지 네트워크 실패시 UI 개선

---

src/component/rent/RentModalBook.tsx

- fixes #496
대출 인식 성공 후 바로 close하면
id로 책정보가져오는 요청이 진행되지 않음

fix: 대출 QR 인식 성공때는 closeModal 실행안되도록 수정

---

src/api/bookInfo/useGetBookInfoReviews.ts
src/api/reviews/useDeleteReviewsReviewsId.ts
src/api/reviews/usePostReview.ts
src/api/reviews/usePutReviewsReviewsId.ts
src/asset/css/Review.css
src/component/book/review/PostReview.tsx
src/component/book/review/Review.tsx
src/component/book/review/ShowReviews.tsx
src/component/mypage/MyReview.tsx
src/component/mypage/Mypage.tsx
src/component/utils/HandleReview.tsx

- 42library와 현재 develop 간 UI 오류를 해결했습니다
- 기타 코드 가독성 개선을 위한 리팩토링을 진행했습니다. 
- fixes #495
- api 호출부 분리
- 마이페이지 탭 아래 선 추가
- 마이페이지 책 제목 클릭시 해당 상세페이지로 이동
- 기타 변수명 변경
|페이지|캡처이미지|
|---|---|
|마이페이지 UI 일치|<img width="1553" alt="image" src="https://github.com/jiphyeonjeon-42/frontend/assets/74622889/7fd775a6-26d2-4c0a-a4b6-a12e15fe9e8f">|
|상세페이지 UI 일치|<img width="1556" alt="image" src="https://github.com/jiphyeonjeon-42/frontend/assets/74622889/99d25c2b-2fc2-4c61-a9c7-6fa3f42575e1">|
|리뷰 등록시 알림|![Jul-19-2023 02-00-08](https://github.com/jiphyeonjeon-42/frontend/assets/74622889/80d7ffed-7569-415b-8d05-2639a5cc0f25)|
###

refactor: 리뷰 리팩토링 및 UI 오류해결

---

src/api/books/useGetBooksInfoNew.ts
src/api/books/useGetBooksInfoPopular.ts
src/component/main/MainNewBook.tsx
src/component/main/MainNewBookList.tsx
src/component/main/MainPopularCenter.tsx
src/component/main/MainPopularSide.tsx

- fixes #519
- 메인 인기도서 및 메인페이지의 책타입 변경 
- 책정보에 해당하기 때문에 BookInfo가 더 적절
- 인기도서 rank 속성 추가 `(BookInfo & { rank: number })[];`
- book.rank 타입오류, rank는 없는 속성 
- 네트워크 반환받은 값에 rank 값 추가 index + 1
|before|after|
|---|---|
|![https://user-images.githubusercontent.com/85754295/254524735-5aa499d1-b7f8-4184-9479-a806731c2abd.png](https://user-images.githubusercontent.com/85754295/254524735-5aa499d1-b7f8-4184-9479-a806731c2abd.png)|<img width="1120" alt="image" src="https://github.com/jiphyeonjeon-42/frontend/assets/74622889/6f79e2b2-6b5e-4678-9a47-cdc0fee12ae4">|

fix: 메인페이지 인기 도서 순위 오류 해결

---

src/component/bookManagement/BookManagementModalDetail.tsx

도서 수정 페이지에서 수정 요청을 보낼시 categoryId가 문자열로 보내져 연산에 오류가 생기는 문제가 있었습니다.

fix: 도서 수정 categoryId를 숫자로 변경

---

src/asset/css/MainBanner.css
src/asset/img/scroll-icon.svg
src/component/main/MainBanner.tsx

- svg 이미지 대신 css로 마우스형태 구현
- 애니메이션 동작 추가
||화면|
|---|---|
|before|![Aug-16-2023 19-43-55](https://github.com/jiphyeonjeon-42/frontend/assets/74622889/da960b4b-9ce7-49cf-b04f-a2e53ab13c41)|
|after|![Aug-16-2023 19-45-14](https://github.com/jiphyeonjeon-42/frontend/assets/74622889/06948d42-c0a6-4a2a-a830-473ba77824c6)|
- fixes #533

feat: 메인페이지 스크롤을 내려주세요 애니메이션 추가

---

src/component/utils/Image.tsx

- error state 삭제
- 에러가 발생하면 img 엘리먼트의 src값이 바뀌도록 수정
- fixes #441

fix: Image 컴포넌트 에러 처리 방식 변경

---

package.json
pnpm-lock.yaml
src/api/like/index.ts
src/component/mypage/MyRentInfo/MyRent.tsx
src/component/mypage/MyRentInfo/RentHistory.tsx
src/component/mypage/MyRentInfo/RentHistoryTable.tsx
src/component/mypage/MyRentInfo/RentedOrReservedBooks.tsx
tsconfig.json
vite.config.ts

- fixes #541
1. 절대경로 `~`를 사용해 import를 할 수 있도록 `tsconfig.json`에 `paths` 매핑을 추가했습니다.
2. vite가 개발 모드와 빌드 시 `paths`를 이해할 수 있게 `vite-tsconfig-paths` 플러그인을 추가했습니다.
3. 사용 예시를 들기 위해 `src/component/mypage/MyRentInfo`의 import를 절대 경로로 변경했습니다.

build: 절대경로 import 추가, `MyRentInfo`에 절대경로 적용

---

src/component/mypage/Mypage.tsx
src/component/userManagement/UserBriefInfo.tsx
src/util/date.ts

- 중복되는 대출 제한일 계산 로직 통합 및 가독성 개선
- 타입스크립트에 필요하지 않은 타입체크 코드 삭제
- addDay() 날짜 오류 해결
자세한 내용은 files changed 를 참고해주세요!
- fixes #465

refactor: 대출제한일 계산 로직 통합

---

src/asset/css/SearchBar.css
src/asset/css/SearchBarDropDown.css
src/component/main/MainBanner.tsx
src/component/search/SearchBanner.tsx
src/component/superTag/SuperTagMergeDefaultTag.tsx
src/component/userManagement/UserManagement.tsx
src/component/utils/BookSearchBar.tsx
src/component/utils/BookSearchPreview.tsx
src/component/utils/BookSearchRecentKeywords.tsx
src/component/utils/InquireBoxTitle.tsx
src/component/utils/Management.tsx
src/component/utils/ManagementSearchBar.tsx
src/component/utils/SearchBar.tsx
src/component/utils/SearchBarButton.tsx
src/component/utils/SearchBarDropDown.tsx
src/component/utils/SearchBarInput.tsx
src/component/utils/SearchModal.tsx

검색창을 Compound 패턴으로 개선합니다
https://www.patterns.dev/posts/compound-pattern
- SearchBar 컴포넌트는 여러 상황을 대비해서 다양한 props를 요구하고 props에 맞게 UI를 구성해왔습니다.
- 또다른 UI 추가 및 변경을 하려면 내부 로직을 변형하여 사용해야 합니다 이 경우 기존 UI에 영향을 주지는 않는지 계속 확인해야 합니다
- compound pattern을 적용해서 확장에 유연하도록 개선합니다
- 최근검색어, 검색 결과 미리보기 같은 도서 검색에서만 쓰이는 기능을 가진 컴포넌트가 필요합니다
- 어드민의 검색창은 영향을 받지 않도록 분리합니다
- BookSearchBar와 ManagementBar는 용도에 따라 SearchBar에 필요한 기능을 넣은 컴포넌트
- SearchBar는 Input, button, dropwon 등 하위 구성요소를 가짐, 하위 구성요소의 다양한 조합으로 활용가능
- BookSearchBar는 Focus되었을때 드롭다운이 보이고 검색어의 유무에 따라 최근검색어/검색결과미리보기를 보임
- 반응형 변화에 맞춰 적절한 위치에 보입니다
- fixes #550

refactor: 검색창 컴포넌트 개선 및 드롭다운 UI 추가

---

src/asset/css/BookSearchRecentKeyword.css
src/component/utils/BookSearchBar.tsx
src/component/utils/BookSearchRecentKeywords.tsx

최근 검색어를 보여줍니다 
- blocked by #551 
- fixed #548
- 검색창 focus + 검색어 입력이 없을 시 최근 검색어 목록을 보여줍니다
- 새로운 단어 검색시 최근 검색어에 추가됩니다
- 검색어 옆 X 버튼으로 삭제할 수 있습니다
- 검색어를 클릭하면 해당 검색 결과를 볼 수 있습니다
||이미지|
|---|---|
|검색어 추가 및 검색 결과로 이동|![Aug-21-2023 15-20-16](https://github.com/jiphyeonjeon-42/frontend/assets/74622889/ee58bae7-89a8-415a-9cf6-a9b5bf453af4)| 
|이미 최근 검색어에 있을시 추가되지 않음|![Aug-21-2023 16-04-22](https://github.com/jiphyeonjeon-42/frontend/assets/74622889/fee12847-e947-4645-b766-2d4db9da1ccf)|
|검색어 삭제|![Aug-21-2023 15-25-56](https://github.com/jiphyeonjeon-42/frontend/assets/74622889/7ceef9ae-e8f8-48c9-9942-778d239bc5a2)|
|검색어 길이가 긴 경우|![Aug-21-2023 15-28-23](https://github.com/jiphyeonjeon-42/frontend/assets/74622889/ba987715-e854-4c14-bb6a-8f3e398defe6)|

feat: 최근 검색어 기능 구현

---

src/asset/css/Carousel.css
src/asset/css/MainNew.css
src/component/main/MainNewBook.tsx
src/component/main/MainNewBookList.tsx
src/component/utils/Carousel.tsx
src/component/utils/CarouselContainer.tsx
src/component/utils/CarouselList.tsx
src/component/utils/CarouselNext.tsx
src/component/utils/CarouselPagination.tsx
src/component/utils/CarouselPrev.tsx
src/component/utils/CarouselRoot.tsx
src/component/utils/Tooltip.tsx
src/hook/useBound.ts
src/hook/useInterval.ts
src/hook/useResponsiveWidth.ts

메인페이지 신규도서 부분 코드에서 carousel UI와 관련된 부분을 추출했습니다.
이 Carousel을 활용해서 인기 검색어와 추천도서 UI를 구현할 예정입니다
- fixes #559
| 이미지 | 설명|
|---|---|
|![Aug-29-2023 00-04-28](https://github.com/jiphyeonjeon-42/frontend/assets/74622889/6772806b-82d1-4258-8f90-34bf03629365)|버튼으로 조작가능, 처음과 끝의 전환이 자연스럽게 넘어감|
|![Aug-29-2023 00-06-35](https://github.com/jiphyeonjeon-42/frontend/assets/74622889/10e317ce-f8fc-472b-b3eb-ee64f4ba64bf)|hover 시 애니메이션 멈춤, 떠나면 재시작|
- story를 짜서 활용방법도 같이 다루면 좋겠지만 경진대회 일정상 스토리까지는 추가하지 못했습니다
- 관련된 내용을 최대한 주석으로 담았습니다 9월 중순쯤에 스토리에 반영하겠습니다

feat: carousel UI 컴포넌트 추가 및 메인페이지에 적용

---

src/hook/useApi.ts

useApi 활용방식 추가 
- ts-rest 도입이 완료될때까지 useApi를 활용해야 합니다
- 현재 useApi의 request는 url과 data가 훅 호출 시점에 결정되어 랜더링이 바뀌기 전의 값이 고정됩니다
- 실제 api 호출 시점에 url과 data를 결정할 수 있도록 하는 requestWithUrl 함수를 추가했습니다 
- fixes #563

fix: useApi 임시 활용방법 추가

---

src/component/utils/BookSearchBar.tsx

최대 10개로 제한하기 위해 검색어 추가시 slice 해서 저장합니다
- fixes #571

fix: 최근 검색어 최대 10개로 제한

---

src/component/utils/BookSearchPreview.tsx
src/component/utils/SearchRankingList.tsx

인기검색어에서 클릭시 검색어가 제대로 보이지 않는 문제를 해결했습니다. 
- fixes #574 
입력어포함 URL로 이동할때 특수문자를 위한 인코딩추가

fix: 도서 검색 리다이렉트시 URI 인코딩 추가

---

src/component/book/BookDetail.tsx

- fixes #531 
https://github.com/jiphyeonjeon-42/backend/blob/bfbb03c68601f812bf43763e9c0544c9907853fc/backend/src/v1/books/books.service.ts#L397
처음부터 백엔드에서 돌려줄 때 청구기호 순으로 정렬해 돌려주는 것도 좋을 것 같습니다.

feat: 도서 상태 정보를 청구기호 순으로 정렬

---

src/api/books/useGetBooksCreate.ts
src/api/books/usePostBooksCreate.ts
src/component/addbook/AddBook.tsx
src/component/addbook/AddBookDisplayBasicBookInfo.tsx
src/component/addbook/AddBookRegisterBookWithUsersExtraInput.tsx
src/type/BookInfo.ts

카테고리가 제대로 선택되지 않던 문제를 수정했습니다
- fixes #528
- GET "books/create"의 응답값 koreanDemicalClassification 속성 대신 category로 전달되고 있었음
- 개발/비개발 카테고리 상태값은 boolean인데 select option값은 string 형식 => 비교 코드가 복잡하게 꼬임
- 개발/비개발 카테고리 상태값 "" | "true" | "false"로 변경 및 오류 수정
- 네트워크 요청 시 불필요한 타입체크 (expectedItem 등) 삭제
- 네트워크 요청 시 코드 단순화 request, useEffect => requestWithUrl
- GET "books/create"의 응답값 koreanDemicalClassification 속성 사라진 점 대응
- 새로고침 방식 변경 window.location.reload() => navigate(0)
- 상대경로 중 일부 절대경로로 수정 ../../ => ~/
- 기타 타입 오류 해결
|화면 | 설명|
|--|--|
|<img width="1260" alt="스크린샷 2023-11-29 오후 2 05 43" src="https://github.com/jiphyeonjeon-42/frontend/assets/74622889/e7a622df-cb12-4c93-8414-7fe097fdf47c">|초기 카테고리 기본값|
|<img width="1260" alt="스크린샷 2023-11-29 오후 2 10 38" …

fix: 도서등록 카테고리 제대로 적용되지 않던 문제 수정

---

src/component/utils/ManagementSearchBar.tsx

바코드 이미지로 변경했습니다
SearchBar => ManagementSearchBar로 변경하는 과정에서 글씨로 변경되었던 점을 다시 복구했습니다
- fixes #596
|변경전| <img width="1224" alt="스크린샷 2023-11-29 오후 2 30 57" src="https://github.com/jiphyeonjeon-42/frontend/assets/74622889/5d280d0b-94d4-4775-a573-1201507ed6e0">|
|---|---|
|변경후|<img width="1224" alt="스크린샷 2023-11-29 오후 2 30 38" src="https://github.com/jiphyeonjeon-42/frontend/assets/74622889/cdc9acb0-92a7-4c46-9b55-95ae5b32d61f">|

fix: 바코드 버튼 글씨 대신 이미지로 변경

---

package.json
pnpm-lock.yaml
src/App.tsx
src/config/sentry.ts
src/env.d.ts
src/index.tsx
src/util/axios.ts

- fixes #604
- BrowserTracing import 방식이 아주 오래전 방식
- 조만간 패키지 자체가 사라질 수도 있어서 수정 필요
https://github.com/getsentry/sentry-javascript/issues/8796 
- BrowserTracing 방식 수정, react-router에 맞는 통합 설정 적용
- Replay 설정 추가
- 센트리 설정 코드가 길어져서 config/sentry.ts로 분리
- env REACT_APP_ENV 추가
- 기존 코드는 개발서버/테스트서버 등에 대처하기 어려웠음
- 백엔드 api로 유추하는 실행환경 대신 직접적으로 명시
- axios 오류 상황뿐만 아니라 UI 랜더링 오류등 기타 클라이언트 오류도 잡히도록 ErrorBoundary 설정
https://docs.sentry.io/platforms/javascript/guides/react/features/react-router/
https://docs.sentry.io/platforms/javascript/guides/react/session-replay/
- 센트리, 구글GA 연결된 계정 
- library4242 Google
- 인증정보는 슬랙 참고
- 사용자 환경에서의 성능 측정이 가능 
- lighthouse와 함께 성능 최적화 작업때 도움이 될 것
- 에러가 발생한 직전 상황을 확인할 수 있음 
- 유저의 동작을 참고해서 에러 상황을 재연할 때 도움이 될 것

fix: 센트리가 제대로 동작하지 않는 문제 수정

---

src/component/addbook/AddBookRegisterBookWithUsersExtraInput.tsx

제대로 동작하지 않은 오류 수정
- Select에서 선택시 useSatete의 값들이 올바르게 설정되도록 수정
- 개발/비개발 영역 새로운 값 선택시, 카테고리 아이디는 ""로 초기화
- 중앙도서관분류를 사용하는 부분은 무엇이 의도인지 몰라 우선 삭제 (추후 체크후 추가 커밋 필요할수도)
오류 수정 외
- donator 받는 input 영역도 useState로 수정
- donator도 required 옵션 부여 && isReadyToPost에 반영
도서 등록 select 태그를 사용한 드롭다운 버튼이 제대로 동작하지 않는 오류를 수정했습니다.
- fixes #606

fix: 도서 등록 폼에 카테고리 선택 코드 수정

---

package-lock.json
src/asset/css/BookInformationWithCover.css
src/asset/css/RentInquireBoxBook.css
src/asset/css/TextareaWithLabel.css
src/component/rent/Rent.tsx
src/component/rent/RentConfirm.tsx
src/component/rent/RentInquireBoxBook.tsx
src/component/rent/RentInquireBoxUser.tsx
src/component/rent/RentModalConfirm.tsx
src/component/rent/RentModalUserList.tsx
src/component/utils/TextareaWithLabel.tsx
src/constant/status.js

사서의 대출권수를 4권으로 변경했습니다. (사서의 특권)
사서 본인이 본인의 대출을 진행할 때만 4권까지 가능합니다. 이는 앞으로 개발 될 예정인 집현전의 무인화 및 코드작성 편의를 고려하여 설정한 조건입니다.
#619 
* 대출 진행 시 사서 표시하는 UI 추가
* 대출 확인 모달의 도서 간 경계 및 비고란의 배경색 추가

feat: 사서 대출권수 변경

---

index.html
package-lock.json
package.json
pnpm-lock.yaml
src/App.tsx
src/component/book/BookDetail.tsx
src/component/utils/HelmetComponent.tsx
src/index.tsx
vite.config.ts

- #618 
기존 집현전 책 링크 공유시 위와 같이 기본 설명만 떠서 어떤 책인지 바로 알기 어려움.
1. 오픈 그래프 태그가 동적으로 변해야함.
2. 동적으로 변한 태그를 크롤러가 잘 가져가야함.
1. [react-helmet-async](https://www.npmjs.com/package/react-helmet-async) 를 이용해서 meta 데이터 수정 ([a9bb590](https://github.com/jiphyeonjeon-42/frontend/pull/621/commits/a9bb590bc8c68068fd82865af4643f812921fbd1),[de4c5f4](https://github.com/jiphyeonjeon-42/frontend/pull/621/commits/de4c5f4da88da3d27b9ee850b9b724aa2fa978fd))
2. (미완) 동적 렌더링(by [prerender](https://www.npmjs.com/package/@prerenderer/rollup-plugin))을 사용해서 크럴러에게는 미리 만들어진 책 정보들을 넘김. ([7775c08](https://github.com/jiphyeonjeon-42/frontend/pull/621/commits/7775c087b7ae6c2413e980f4841b2848256e723a))
- 배포후에도 정상 작동하는지 확인 필요.
- 동적 렌더링이 장기적인 권장사항이 아님으로 SSR을 지원하는 프레임워크나 리액트 19에서 도입되는 서버사이드 컴포넌트를 고려해봄직함.

feat: 책 링크 공유시 해당책에 이미지와 설명 미리보기로 보여주기

---

.github/workflows/deploy-main.yml
appspec.yml
scripts/start.sh
scripts/stop.sh

ci: 자동배포용 스크립트

---

.github/workflows/deploy-main.yml
appspec.yml
scripts/start.sh
vite.config.ts

코드 디플로이를 이용한 자동배포 최종 merge입니다.

ci: 자동배포 최종 main 머지

---

src/asset/css/Tags.css
src/component/book/tag/TagList.tsx
src/component/utils/Tooltip.tsx
src/util/axios.ts

아래의 버그를 수정했습니다.
1. 모바일에서 화면 밀리는 버그
2. 태그 안의 텍스트가 잘리는 버그
3. 2번을 진행하면서 태그의 특정 입력값에 따른 에러핸들링을 추가했습니다.
a. 비로그인 시, 태그 제출이 불가능하도록 버튼을 비활성화하고 에러코드를 활성화시켰습니다.
b. 빈 값, 'ㄴ' 같은 자음, 중복된 태그일 때 에러핸들링이 되어있지만 onError로 가지 않고 onSuccess로 가는 것을 확인하여 onSuccess에서 추가 처리했습니다.
c. 기존 코드에 setter 함수로 에러코드를 설정하고 바로 태그 등록하는 로직이 있었고, setter 함수는 async가 내부에 있기때문에 에러코드가 바로 바뀌지 않음. 그래서 useEffect로 에러코드 변경에 따른 에러활성화 로직을 추가하고 errorCodeRef(useRef 사용) 변수로 에러를 즉시 감지할 수 있도록 추가했습니다.
d. 중복된 태그, 'ㄴ' 같은 자음 입력값은 프론트에서 처리된 게 아니라 백엔드에서 처리됐는데 onError로 오지 않고 onSuccess로 받고 있기때문에 (정확한 원인 모름) 콘솔에서 400에러가 뜨고 있음 => 알수없는 에러로 모두 처리
=> d 에 대한 에러 원인 해결을 [하단](#-400-에러를-못잡는-현상을-고친-방법)에 적어놨습니다.
#629 
이번 주 프론트 미팅을 진행하면서 @YeonSeong-Lee 님이 도와주셨습니다 🥺
**변경 전**
```typescript
// axios.ts
api.interceptors.response.use(
response => response,
error => …
```

fix: 모바일화면에서 화면이 밀리는 현상 및 태그기능 버그 수정

---

src/component/rent/RentModalBooks.tsx
src/component/rent/RentModalConfirm.tsx
src/component/reservedloan/ReservedModalContents.tsx
src/component/return/ReturnModalContents.tsx
src/component/search/BookInfo.tsx
src/component/search/CategoryFilter.tsx
src/component/search/Search.tsx
src/component/search/SearchBanner.tsx
src/component/search/SearchSection.tsx
src/component/search/Sort.tsx
src/component/search/WishBook.tsx
src/component/utils/BookInformationWithCover.tsx
src/component/utils/Button.tsx
src/component/utils/CarouselContainer.tsx
src/component/utils/CarouselList.tsx
src/component/utils/Pagination.tsx
src/component/utils/Paginations.tsx
src/component/utils/SearchRankingItem.tsx
src/component/utils/SearchRankingList.tsx
src/component/utils/SubTitle.tsx
src/component/utils/TextWithLabel.tsx
src/component/utils/TextareaWithLabel.tsx

불필요한 리렌더링을 최적화하여 애플리케이션의 성능을 개선했습니다.
**개선 전** | **개선 후**
:---: | :---:
**개선 전** | **개선 후**
:---: | :---:
**개선 전** | **개선 후**
:---: | :---:
- Resolves #633
- 제어 컴포넌트와 비제어 컴포넌트

refactor: 렌더링 최적화

---

src/component/utils/BarcodeReader.tsx

- fixes #634 
- 기본기기 처음-> 마지막
- window.alert 대신 Dialog로 대체
- alert API가 동기함수라서 아예 자바스크립트가 멈춰버림

fix: 634 바코드리더 초기값 변경

---

src/api/books/useGetBooksInfoSearchUrl.ts
src/component/book/BookDetail.tsx
src/component/search/Search.tsx
src/component/utils/HeaderMobile.tsx

- 문제
- 이전 페이지에서 스크롤한 상태일 때, 특히 메인에서 진입시 스크롤 이상함
- 데스크탑 : 스크롤 중간쯤
모바일 : 스크롤 최상단
- breadCrumb 쪽에 scrollIntoView 코드가 들어있지만 제대로 동작하지 않음
- 원인 및 해결
- 책정보 api가 호출 되기 전 랜더링된 화면에는 scrollIntoView에 연결된 ref가 없음
- ref.current를 의존성에 추가, ref가 이후 마운트 되더라도 영향을 받도록 
- 뒤로가기 클릭시 스크롤이 초기화되는 문제
- 도서 목록등에서 보고있는 스크롤 위치로 돌아가지 않음
-> 책 상세 진입시 이전 화면의 스크롤 위치를 기억해두고 돌아갈때 다시 설정되도록
- 도서목록으로 진입시 기존스크롤에 영향받는 문제
- 모바일 화면에서만 문제가 됨
- 데스크탑은 헤더가 최상단에서만 보임, 기존 스크롤 위치가 문제되지 않음
-> 모바일 헤더버튼에 최상단으로 스크롤 올리는 로직 추가
|before|after|
|---|---|
|![before](https://github.com/user-attachments/assets/339ab15e-cb44-47c4-8d2e-9a0f6b562257)|![Nov-17-2024 21-00-51](https://github.com/user-attachments/assets/d014ade6-295e-4cd7-9604-5767d1aebbef)|

fix: 책 상세 진입때 스크롤 관련 버그

---

src/asset/css/reset.css

IOS에서 기본값으로 설정되는 파란색을 검정색으로 설정
[IOS 파란색](https://ramincoding.tistory.com/entry/IOS-%EC%9B%B9%EB%B7%B0-%ED%99%94%EB%A9%B4-button-or-a-%ED%83%9C%EA%B7%B8-%ED%85%8D%EC%8A%A4%ED%8A%B8-%EC%83%89%EC%83%81-%ED%8C%8C%EB%9E%80%EC%83%89%EC%9C%BC%EB%A1%9C-%EB%82%98%EC%98%A4%EB%8A%94-%EB%AC%B8%EC%A0%9C-%ED%95%B4%EA%B2%B0)

fix: ios에서 파란색으로 보이는 버그 수정

---

src/component/information/Information.jsx

연체 안내와 무인대출/반납 관련 문구 수정
- fixes #649 
- 무인대출 안내문구 수정도 같이 했습니다. 브런치이름과는 안 맞지만...

chore: 안내문구 수정

---

src/api/books/usePatchBooksUpdate.ts
src/api/lendings/useGetLendingsSearchId.ts
src/api/lendings/usePatchLendingsReturn.ts
src/api/lendings/usePostLendings.ts
src/api/lendings/usePostLendingsMultiple.ts
src/api/reservations/usePatchReservationsCancel.ts
src/api/reservations/usePostReservations.ts
src/api/reviews/usePatchReviewsId.ts
src/api/reviews/usePostReview.ts
src/api/stock/usePatchStockUpdate.ts
src/api/tags/useDeleteTagsSuper.ts
src/api/tags/usePatchTagsSub.ts
src/api/tags/usePostTagsSuper.ts
src/api/users/usePatchUsersMyupdate.ts
src/api/users/usePostUsersCreate.ts
src/component/mypage/EditEmailOrPassword.tsx
src/component/mypage/Mypage.tsx
src/component/rent/RentModalBook.tsx
src/component/return/ReturnModalContents.tsx
src/component/utils/BarcodeReader.tsx
src/component/utils/HandleReview.tsx
src/component/utils/HiddenModal.jsx
src/hook/useNewDialog.ts
src/hook/usePermission.ts

- fixes #652 - 도서 반납 시 패널티 관련 메시지 개선
- 연체 일수만큼 대출 제한 메시지 표시
- 기존 패널티와 신규 연체 일수의 합계 표시
- 기존 패널티 일수 안내
- 일반 반납 완료 메시지
- 패널티 메시지 로직 개선
- 음수 패널티 방지 로직 추가
- 메시지 포맷 일관성 개선

feat: 반납시 대출불가일 안내
