package-lock.json, package.json, src/App.js, src/component/Banner.js, src/component/BookDetail.js, src/component/BookInfo.js, src/component/BookStatus.js, src/component/Books.js, src/component/Footer.js, src/component/SearchBar.js, src/component/SearchDetail.js, src/component/SearchLoader.js, src/css/Banner.css, src/css/BookDetail.css, src/css/BookInfo.css, src/css/BookStatus.css, src/css/Books.css, src/css/Footer.css, src/css/SearchBar.css, src/css/SearchLoader.css
=> FEATURE : 라우터 변경 및 상세페이지 추가

public/index.html, src/css/reset.css
=> MERGE : ENV 기본 적용 css 추가

src/App.css, src/App.js, src/component/BackGround.js, src/component/BookInfo.js, src/component/Books.js, src/component/Header.js, src/component/Information.js, src/component/Main.js, src/component/MainHome.js, src/component/MainNew.js, src/component/MainPopular.js, src/component/Question.js, src/component/Search.js, src/css/BackGround.css, src/css/BookInfo.css, src/css/Books.css, src/css/Header.css, src/css/Infomation.css, src/css/MainHome.css, src/css/MainNew.css, src/css/MainPopular.css, src/css/Question.css, src/css/Search.css
=> MERGE : REFACTOR 1440px 이상 화면에서의 반응형 여백 수정

src/component/MainNew.js, src/css/MainNew.css
arrowbox에 걸린 flex 때문에 신작도서 링크가 걸리지 않는 점 수정했습니다!
=> MERGE: FIX arrowbox flex 설정해제

src/component/MainPopular.js, src/css/MainPopular.css
카카오 api 대신 localhost:3001 적용했습니다
=> MERGE: FIX 인기도서 백엔드 api 적용

package.json, src/App.js, src/atom/userState.js, src/component/Auth.js, src/component/Header.js, src/component/Logout.js
=> MERGE: FEATURE 로그인 api 연결

src/component/MainNew.js, src/component/MainPopular.js, src/css/MainNew.css, src/css/MainPopular.css
=> MERGE : FEATURE 신작도서 페이지네이션 추가

src/css/MainPopular.css, src/css/MainPopularBook.css
=> MERGE FIX 인기도서 픽셀값 수정

.github/ISSUE_TEMPLATE/----------.md
=> 이슈 템플릿을 추가합니다.

src/component/Books.js, src/component/Header.js, src/index.js
#32 
withCredential option 추가
api url 변경
=> ENV: withCredential option 추가, api url 변경

src/component/Auth.js, src/component/Header.js, src/component/Logout.js
me api 호출한 내용을 로컬스토리지에 저장하는 부분을 수정했습니다.
=> MERGE: FIX: 로그인 오류 수정

src/atom/categories.js, src/atom/page.js, src/atom/sortBy.js, src/component/BookDetail.js, src/component/BookInfo.js, src/component/Books.js, src/component/CategoryFilter.js, src/component/MainPopular.js, src/component/Pagination.js, src/component/Search.js, src/component/SearchBar.js, src/component/Sort.js, src/css/BookStatus.css, src/css/Question.css, src/css/Search.css, src/css/SubTitle.css, src/css/Title.css
모달창 기능 연습과 코드리뷰를 바탕으로 진행한 코드 리팩토링(전역 state -> 지역 state)
=> MERGE : FEATURE (모달창 구현) 및 REFACTOR(전역 -> 지역 state)

src/App.js, src/component/Search.js, src/component/SearchBar.js
=> MERGE: REFACTOR: 검색 예외처리 인코딩/디코딩 추가

src/App.js, src/Routes.js, src/component/utils/Header.js
=> MERGE : FEATURE : 비로그인유저 특정페이지 접근 제한

src/component/book/BookStatus.js, src/component/main/MainPopular.js, src/component/rent/RentModal.js, src/component/reservedloan/ReservedModal.js, src/component/utils/MidModal.js, src/component/utils/MiniModal.js, src/css/MainNew.css, src/css/MainPopular.css, src/css/MiniModal.css, src/img/arrow_left.svg, src/img/arrow_right.svg
=> MERGE: 11월 1일 집현전회의 피드백 반영

src/component/reservedloan/ReservedFilter.js, src/component/reservedloan/ReservedLoan.js, src/component/reservedloan/ReservedModal.js, src/component/return/ReturnBook.js, src/component/return/ReturnBookTable.js
FIX : 반납테이블 텍스트, 타이틀, POST요청 및 스크롤문제 수정
=> FIX : 반납테이블 텍스트, 타이틀, POST요청 및 스크롤문제 수정

src/component/main/MainHome.js, src/component/main/MainNew.js, src/component/main/MainNewBook.js, src/component/main/MainNewBookList.js, src/component/main/MainNewBookPagination.js, src/component/main/MainPopular.js, src/css/MainHome.css, src/css/MainNew.css, src/css/MainPopular.css
> 메인화면 신작도서 부분의 코드를 기능 및 역할별로 분리했습니다
- MainNew.js : 서버에서 데이터를 가져오는 역할만 수행
- MainNewBookList.js : 신작도서 목록을 구성하고 이벤트에 맞는 동작 수행
- MainNewBook.js : 신작도서 목록들 중 각 도서의 이미지 및 링크 노출
- MainNewPagination.js : 신작도서 목록 하단의 원형 버튼 노출
MainHome, MainNew, MainPopular의 className이 뒤죽박죽이었던 점을 수정했습니다.
=> REFACTOR: 메인 신작도서 코드 리팩토링

src/component/search/Available.js, src/component/search/BookInfo.js, src/component/search/CategoryFilter.js, src/component/search/Pagination.js, src/component/search/Search.js, src/component/search/SearchBar.js, src/component/search/Sort.js, src/css/Available.css, src/css/Search.css, src/css/Sort.css
=> 검색페이지 컴포넌트에 propTypes 추가 및 오류메세지 제거

src/css/Header.css
=> REFACTOR: Header의 대출/반납 버튼 정렬 수정

src/component/book/BookStatus.js, src/component/login/Auth.js, src/component/main/Main.js, src/component/main/MainNew.js, src/component/main/MainPopular.js, src/component/main/MainPopularBookList.js, src/component/rent/RentModalContents.js, src/component/reservation/Reservation.js, src/component/reservation/SuccessRsv.js, src/component/reservation/UserConfirm.js, src/component/reservedloan/ReservedLoan.js, src/component/reservedloan/ReservedModal.js, src/component/reservedloan/ReservedModalContents.js, src/component/return/ReturnBook.js, src/component/return/ReturnModal.js, src/component/return/ReturnModalContents.js, src/component/utils/MidModal.js, src/component/utils/MiniModal.js, src/component/utils/ModalContentsOnlyTitle.js, src/component/utils/ModalContentsTitleWithMessage.js, src/component/utils/error.js, src/css/MiniModal.css
> 모달 관련 코드를 기능 및 역할별로 분리했습니다 400 에러시 서버에서 전달받은 에러코드에 따라 안내문을 표시합니다.
> - utils/MiniModal.js : 경계 밖을 클릭하면 꺼지는 모달, 사이즈 작음
> - utils/MidModal.js : 경계 밖을 클릭해도 꺼지지 않는 모달, 사이즈는 중간
> - RentModal, ResevedModal, Returnmodal : 미드 미니 모달 간 창 전환, 모달들의 내용을 결정
> - RentModalContents, ReservedModalContents, ReturnModalContents  : 모달안에서 화면을 구성하는 파일들
> - reservation/Resevation.js : 예약 POST 요청을 보내고 그 결과에 따라 미니모달의 내용을 변경함
> - reservation/UserConfirm.js : 서버요청 전 예상 순위 노출 및 사용자 재확인 
> - reservation/SuccessRsv.js : 성공시 바뀔 미니모달의 내용 
> - utils/ModalContentsOnlyTitle : 간단한 미니모달을 구성할 때 사용 타이틀만 전달가능
> - utils/ModalContentsTitleWithMessage : 간단한 미디모달 구성, 타이틀 및 하위 텍스트 전달가능
- utils/error.js : HTTP 400 오류시 url 및 오류코드에 따라 메세지 전달
MainPopularBookList.js 계산식을 간소화했습니다.
모호한 handleModal 표현대신 closeModal 로 변경하였습니다. 
문자열의 이스케이프문자, …
=> REFACTOR: 모달 리팩토링 및 400 에러코드 대응

src/css/reset.css
#110 reset.css에서 html를 개별요소로 나눈뒤, 1rem = 10px 설정을 위해 font-size를 62.5%로 변경
=> ENV: REM 크기 10px로 설정

src/component/main/MainPopular.js, src/component/main/MainPopularCenter.js, src/css/MainNew.css, src/css/MainPopular.css, src/css/SubTitle.css
#112
수정사항 
2. 헤더보다 높은 z-index 조정 (신간도서 booklist, 화살표)
3. subtitle 줄바꿈으로 신간도서 배치가 어긋나는 현상
4. 인기도서 하단 여백 조정
5. 기타 인기도서 부분 767px 이하에도 최적화되도록
6. 인기도서 -> 도서 상세 페이지이동 동작 추가, 선택된(펼쳐진) 상태에서 클릭했을때는 해당 도서상세로 페이지이동
=> FIX: 메인 레이아웃 오류 수정

src/css/BookInfo.css, src/css/Search.css, src/css/WishBook.css
solve #120 
- 모바일 디자인 적용
- 기존의 px -> rem 으로 변경
=> FIX : 도서 검색페이지 - 모바일 디자인 Sample

src/css/AdminTabs.css, src/css/Header.css, src/css/MobileHeader.css, src/css/SearchBanner.css, src/css/Title.css
=> REFACTOR: 검색페이지 배너 높이 조정 및 기타 fix

src/component/search/CategoryFilter.js, src/component/search/Search.js, src/component/search/SearchBanner.js, src/component/search/SearchBar.js, src/css/CategoryFilter.css, src/img/arrow_left_black.svg, src/img/arrow_left_gray.svg, src/img/arrow_right_gray.svg
=> CategoryFilter 스크롤 되도록 수정

src/component/login/Auth.js
- 유효기간 60분 -> 480분(8시간)으로 변경!!
=> JIP-174	localStorage 유효기간 변경

src/component/mypage/EditEmail.js, src/component/mypage/EditPassword.js, src/component/mypage/Mypage.js, src/component/mypage/MypageReservedBook.js, src/component/rent/RentModalConfirm.js, src/component/reservedloan/ReservedFilter.js, src/component/reservedloan/ReservedLoan.js, src/component/reservedloan/ReservedModal.js, src/component/reservedloan/ReservedModalContents.js, src/component/reservedloan/ReservedTableList.js, src/component/return/ReturnModalContents.js, src/css/AdminSearchBar.css, src/css/EditEmail.css, src/css/EditPassword.css, src/css/InquireBoxTitle.css, src/css/MidModal.css, src/css/Modal.css, src/css/Mypage.css, src/css/MypageRentedBook.css, src/css/MypageReservedBook.css, src/css/MypageRoutes.css, src/css/ReservedFilter.css, src/css/ReservedLoan.css, src/css/ReservedTableList.css
아래처럼 `MiniModal`을 띄워줍니다. 이는 데이터를 정상적으로 받아오지 않거나, 이메일 혹은 패스워드를 변경할 때 오류 발생 시에 사용됩니다.
또한 이메일 혹은 패스워드를 변경할 때 `성공 매시지`를 띄워줍니다. 다만 현재 `myupdate`가 완벽히 구현되어 있지는 않아 보이기 때문에 임의의메시지를 사용했습니다.
또한 아래의 에러메시지 역시 고쳐야 할 사항인 듯 보입니다. (**Header가 그대로 노출되는 issue!**)
=> Jip 214 마이페이지 에러 시 mini modal 렌더링

src/component/return/ReturnBook.js, src/component/return/ReturnBookTable.js, src/component/return/ReturnModalContents.js
- api와 관련된 인자 및 반환값 변경
- 페이지네이션 관련 오류 수정 (page-1)
=> Jip 177 반납페이지 관련 api 변화대응

src/component/book/BookDetail.js, src/component/book/BookStatus.js, src/component/search/Search.js, src/component/userManagement/UserBriefInfo.js, src/component/userManagement/UserDetailInfo.js, src/component/userManagement/UserManagement.js, src/component/userManagement/UserUsageInfo.js
- location과 match를 사용하는 BookDetail 컴포넌트는 일단 그냥 두었습니다.
<br>
- 현재는 errorCode만 띄워주고 있지만, 추후 error.js 를 보충하고 코드가 아닌 메세지를 띄우도록 추가 수정할 예정입니다.
=> Jip 219 상세페이지와 유저 정보 페이지 예외 처리 및 주석 제거

package-lock.json, package.json, src/component/login/Register.js, src/component/utils/error.js
- 42 intra 로 로그인 시에 에러 처리 코드 추가 되었습니다.
- MiniModal을 Register에 추가해서 query의 errorCode를 가지고 처리하게끔 했습니다.
[시연 동영상](https://files.slack.com/files-tmb/T039P7U66-F03M2DDFVAR-ccd4ffc8a6/________________________________2022-06-25______________7.17.41.mp4)
=> JIP-222 42 api login 에러 처리

.eslintrc.js
현 eslint 설정으로는 window에서 오류가 발생
->
다양한 운영체제에서 동작하도록 eslint설정을 변경
=> JIP-232 ENV: 다양한 운영체제에 호환되도록 eslint설정 변경

src/component/main/MainPopularCenter.js
- api 변화로 날짜형식이 잘못 노출되던 문제를 해결했습니다
=> JIP-227-메인페이지-api-변화대응

src/component/mypage/Mypage.js, src/component/utils/error.js
마이 페이지에서 42 에러 처리
백엔드에서 먼저 되어야할 PR
https://github.com/jiphyeonjeon-42/backend-express/pull/106
- 인증 성공시 Backend에서 Front Page /auth 주소로 이동시킵니다.
- Local Storage Update를 위해..
- **인증 성공시 Front에서 처리하는 코드는 없습니다**
- 인증 실패시 에러 메세지 출력
- 이미 인증된 회원의 경우
- 다른 계정에서 이미 42 계정이 연결된 경우
=> JIP-222 42 인증하기 에러 처리

src/component/return/ReturnModalContents.js
=> JIP-177 CHORE: 반납 비고 변수명 수정

src/component/book/AddBook.js, src/component/book/AddBookDisplayBasicBookInfo.js, src/component/book/AddBookFetchBasicBookInfoWithIsbn.js, src/component/userManagement/UserManagement.js, src/css/AddBook.css
- 수동입력시 입력값이 제대로 반영되지 않는 문제를 해결했습니다
- 수동입력한 출판연월일이 날짜형식인지 검증합니다
- 제목이 두줄이상 노출되도록 변경했습니다 2줄 이상이 될 경우 스크롤이 생기도록 처리했습니다
- 30rem으로 설정된 miin-width을 36rem으로 변경했습니다
- 이미 등록된 isbn라면 동일한 주번호 및 시리즈 번호를 추천하고 있습니다. 
- 새로운 isbn일 때 새로운 주번호를 추천하고자 합니다. 
- 백엔드와 관련 수정방향을 논의중입니다
- isbn이 검색되지 않은 정보로 수동입력시 추가검토가 필요합니다. 
- 개발팀에 해당 등록건이 발생했다는 사실을 전달할 수 있는 방법을 고민중입니다. 
- slack APP의 경우 백엔드와 동일한 방법으로 메세지를 보낼 수 없는 상황입니다. 프론트에서는 필수 값인 content-type 때문에 CORS 오류가 발생합니다. 이 문제를 해결하기 위해서는 슬랙앱 권한 획득 및 web HOOK url을 받아와야 합니다.
=> JIP-123 도서등록 페이지 피드백 반영

src/component/login/Register.js
- 기존에는 특수기호가 $@!%*#?& 만 가능한 케이스 였음.
- $&+,:;=?@#|'<>.^*()%!- 이런 특수기호를 받을 수 있게 추가!
- 패스워드 양식은 1개의 대소문자 1개의 숫자 1개의 특수문자가 있는 10자 이상 42자 이하 입니다!
=> JIP-244 회원가입 패스워드 정규식 수정

src/component/userManagement/UserBriefInfo.js, src/component/utils/Header.js, src/css/Header.css
- 미인증 및 일반 유저에게는 `대출/반납`과 `DB관리` 탭을 숨깁니다
- 미인증 유저도 사서가 정보를 수정할 수 있게 합니다
=> Jip 242 미인증 및 일반 유저용 헤더 수정

src/component/search/WishBook.js, src/css/WishBook.css
1. 버튼 속에 text 가운데 정렬
2. 전자도서관으로 바로 가기 링크 추가 (env에 전자도서관 링크 추가됨)
[슬랙 링크](https://42born2code.slack.com/archives/C03BAMF3727/p1656510497817099)
=> JIP-250 책 검색 결과가 없을 때 디테일 수정

.github/workflows/main.yml
=> JIP-261 ENV: action 수정

src/component/rent/RentConfirm.js, src/component/rent/RentModalBookList.js, src/component/utils/error.js, src/css/RentInquireBoxUser.css, src/css/RentModalBookList.css
- nickname이 없는 회원은 null로 뜨는 문제 해결
-> 수정전
-> 수정후
- 권한이 없는 유저가 대출할 경우의 오류 메세지 추가
-> 수정전
-> 수정후
- 모바일에서 css 수정
-> 수정전
-> 수정후
-> 수정전
-> 수정후 (폰트 사이즈만 좀 바꿨습니다.. ㅎㅎ;; 불편하면 데스크탑 써랏...)
=> JIP-260 대출 페이지 버그 수정

.github/workflows/main.yml
=> JIP-261 ENV: action수정

.github/workflows/main.yml
=> JIP-261 ENV: action 재수정

src/component/login/Login.js, src/component/login/Register.js, src/component/utils/error.js
- Login 페이지에서도 42 API 미동의시 에러 핸들링 할 수 있게 미니모달 추가
- Login, Register에서 miniModal이 닫히면 history.push를 통해서 다시
주소를 불러오게 하였음
- 에러코드 추가
=> JIP-259 Login, Register 에러 핸들링 추가 및 수정

.github/workflows/main.yml
=> JIP-261 ENV: 환경변수 추가

src/css/RentModalBookList.css
- https://palbok.tistory.com/49?category=960084
=> JIP-266 opacity 값 최적화간 에러

src/component/information/Information.js, src/component/information/Question.js, src/css/Question.css
이용안내 페이지 수정
1. 링크가 링크처럼 보이게 밑줄 추가
2. 사용자경험에 맞게 안내문구 수정
3. 링크가 있을 때 링크로 가도록 Question 컴포넌트 기능 추가
=> JIP-262 이용안내에 링크 잘못 된곳 수정

.github/workflows/main.yml
프론트 브런치 전략이 main 브런치가 운영 브런치로 바뀌었습니다. 
- develop는 브런치는 개발용으로 씀
- main는 develop에서 QA가 되었을 때만 merge
=> JIP-269 main 브런치에 push되었을 때 자동배포되게 현재는 develop

src/component/mypage/MypageReservedBook.js, src/component/reservedloan/ReservedModalContents.js, src/css/MypageReservedBook.css
`/reservations/cancle/` 이 `/reservations/cancel/` 로 되어 있어서 급하게 수정합니다.
백엔드도 `/reservations/cancel/` 로 되어 있어서 둘 다 바꿉니다.
=> JIP-256 FIX:예약대출 및 마이페이지 reservation 취소 엔드포인트 수정

src/component/search/Search.js
search에서 0이 보이는 문제 해결
[JS 논리 연산자](https://ko.javascript.info/logical-operators)
=> JIP-268 FIX: &&연산자 반환값이 보이는 문제 해결

public/index.html
=> JIP-277 FIX: 메타정보 description 수정

src/css/Information.css
- 전체열기 토글 버튼에서 커서모양이 변경되도록 수정했습니다
=> JIP-279 FIX: 이용안내 전체열기 토글 마우스 커서 변경

src/component/utils/Header.js, src/component/utils/HeaderModal.js, src/component/utils/MobileHeader.js
https://user-images.githubusercontent.com/74581396/177000104-19baff32-3b93-4139-b07a-26fa709ff864.mov
<br>
https://user-images.githubusercontent.com/74581396/177000115-d1ffcebb-eafb-4885-a0cc-6fb8854f00a8.mov
=> Jip 263 페이지 이동시 헤더와 모바일 헤더 토글 해제

src/component/information/Information.js, src/component/information/Question.js, src/css/Information.css, src/css/Question.css
- 건의사항 엑셀시트로 연결될 링크 주소는 env에 추가될 예정입니다
- 문구는 임의로 넣었습니다 더 좋은 표현에 대한 수정 의견 편하게 남겨주세요!
- 기존 UI를 유지하면서 버튼 클릭가능한 범위를 넓혔습니다.
- 전후 비교
=> JIP-280 이용안내 건의사항 링크 추가 및 버튼 사용성 개선

src/component/login/Register.js
1. 비어있는 창의 경우에는 오류 메세지가 표시되지 않았음
- 수정전
- 수정후
2. 이메일 형식이 아닌데, form 전송이 되고, backend에서도 그대로 insert가됨... 크리티컬하다!!
- 수정전
그냥 이메일 형식 아니여도 post 전송하였음
- 수정후
=> JIP-285 회원가입시 검증 추가

src/component/information/Information.js, src/component/information/Question.js
- 이용안내 답변에 링크가 걸릴 텍스트, 링크 주소를 직접 추가할 수 있도록 수정하였습니다. 
- 답변 내 링크 위치를 자유롭게 설정할 수 있습니다.
=> JIP-284 FEAT: 이용안내 커스텀 링크 기능 추가

src/component/return/ReturnBook.js, src/component/utils/InquireBoxTitle.js, src/css/AddBook.css, src/css/InquireBoxTitle.css, src/css/RentConfirm.css, src/css/RentInquireBoxBook.css, src/css/RentInquireBoxUser.css, src/css/ReservedLoan.css, src/css/ReturnBook.css, src/css/ReturnBookFilter.css, src/css/ReturnbookTable.css
- 대출/ 반납/ 도서등록에서 반응형 화면의 오류를 수정했습니다
=> JIP-287 대출 반납 도서등록에서 반응형 화면 오류 해결

src/component/book/BookDetail.js, src/data/error.js
- 다만 현재 백엔드에서 donator 정보를 보내주고 있지 않아서 추후에 더 얘기해봐야할 것 같습니다.
<br>
https://user-images.githubusercontent.com/74581396/177047296-d4205c9e-4e68-4d9c-a458-6c14caa936dc.mov
=> Jip 291 도서 상세페이지 기부자 및 에러메세지 표시

src/component/search/Search.js, src/component/userManagement/UserManagement.js, src/css/Search.css
- 도서 검색 페이지와 유저 정보 페이지에서 에러가 발생했을 때 에러 코드대신 에러 메세지를 표시합니다.
- 희망도서 위아래 여백을 좀 더 좁게 조정했습니다
=> Jip 294 도서 검색 페이지와 유저 정보 페이지에서 에러 메세지 표시

src/css/MainPopular.css
- 인기도서의 커서가 변경되도록 했습니다
- 모바일 화면일때 글씨크기를 조정했습니다.
=> JIP-289 메인페이지 인기도서 커서변경 및 글자 크기 조정

src/component/return/ReturnModalContents.js
반납시에 예약된 책이라면 따로 사서가 따로 빼놔야함 
-> 
예약된 책이라는 알림 필요
1. 예약된 책이라면 예약된 책이라는 문구를 추가함.
=> JIP-296 FEAUTRE: 반납시에 예약자가 있으면 알람메시지로 알려줌

src/component/book/BookDetail.js, src/component/book/BookStatus.js, src/component/login/Auth.js, src/component/reservation/UserConfirm.js, src/component/search/CategoryFilter.js, src/component/search/Pagination.js, src/component/search/SearchBar.js, src/component/search/Sort.js, src/css/BookDetail.css, src/css/BookStatus.css, src/data/error.js
`도서 상세페이지 및 예약` -> `도서 상세 및 예약` 으로 수정했습니다.
`,` 붙이는 로직이 잘못되어 수정했습니다.
태블릿 화면에서의 글자크기와 여백을 조정했습니다.
에러 메세지 띄우는 방법을 수정했습니다
=> Jip 299 도서 상세 title css 및 기부자 표시 수정

src/component/rent/RentConfirm.js, src/component/rent/RentInquireBoxBook.js, src/component/rent/RentInquireBoxUser.js, src/component/rent/RentModalBookList.js, src/component/rent/RentModalConfirm.js, src/component/rent/RentModalUserList.js, src/component/reservedloan/ReservedModalContents.js, src/component/return/ReturnModalContents.js, src/css/InquireBoxTitle.css, src/css/RentConfirm.css, src/css/RentInquireBoxBook.css, src/css/RentInquireBoxUser.css, src/css/RentModalBookList.css, src/css/RentModalUserList.css
- 전체적으로 대출페이지의 css를 좀더 자연스럽게 수정했습니다
- InquireBoxTitle 컴포넌트도 조금 고쳤는데, 공통 컴포넌트라 사이드 이펙트를 겪으신분은 제보 바랍니다.
https://user-images.githubusercontent.com/74581396/177384231-1bc08d60-285b-4cfc-aa80-b409c2142f37.mov
<br>
- 예약대출 api 호출부분을 수정했습니다.
=> Jip 302 대출 페이지 qa 1 차

src/component/login/Register.js
- 기존에는 email 양식을  word@word.word[2글자~3글자]로 검사했습니다.
- 지금은 word@word[여러개].word[2글자~3글자]로 하는거 같습니다.
=> JIP-319 FIX: 회원가입 정규식 변경

src/component/utils/Footer.js
- 푸터 #42seoul_club_42jiphyeonjeon에 링크를 추가했습니다
- 색상설정이 되어 있지 않은 부분에 색이 적용되도록 수정했습니다
=> JIP-323 FEAT: 푸터 집현전 채널에 링크 추가

src/component/login/Login.js, src/css/Login.css, src/css/Register.css
- Placeholder 값 수정
- font size 수정
=> JIP-326 CHORE: 로그인창 간단 css 수정

src/component/userManagement/UserBriefInfo.js, src/component/userManagement/UserDetailInfo.js
penaltyEndDate 가 오늘 이후로 지난 분에게는 penaltyEndDate + overDueDay로 연산합니다.
기존에 연체일을 보여주던 로직을 지우고, 새로운 penaltyEndDate 로직으로 넣었습니다.
이제 penaltyEndDate 에 현재 대출중인 책에 대한 연체도 포함됩니다.
현재 시간 + overDueDay 
현재시간 + overDueDay
penaltyEndDate + overDueDay
이 로직으로 연산됩니다.
=> JIP-320 유저관리 연체일 로직 수정

src/component/mypage/Mypage.js, src/css/Mypage.css
기존에 연체일을 보여주던 로직을 지우고, 새로운 penaltyEndDate 로직으로 넣었습니다.
이제 penaltyEndDate 에 현재 대출중인 책에 대한 연체도 포함됩니다.
현재 시간 + overDueDay 
현재시간 + overDueDay
penaltyEndDate + overDueDay
이 로직으로 연산됩니다.
=> JIP-318 마이페이지 연체일 로직 수정

src/component/mypage/Mypage.js, src/component/mypage/MypageRentedBook.js, src/component/mypage/MypageReservedBook.js, src/component/reservedloan/ReservedModalContents.js
=> Jip 328 예약 취소 시에 confirm 추가

.github/workflows/main.yml
최근 추가된 환경변수가 배포단계에서 반영되지 않고 있었습니다. 
- 추가된 환경변수도 함께 처리하도록 yml 파일을 수정했습니다. 
- git secret 에도 환경변수를 미리 넣어두었습니다. 
- 긴급 핫픽스로 보호규칙을 잠시 풀고 이 풀리퀘만 approve를 기다리지 않고 바로 적용할 예정입니다.
=> JIP-336 ENV: 배포단계에 REACT_APP_SUGGESTION 환경변수 반영

src/component/mypage/Mypage.js, src/component/rent/RentInquireBoxUser.js, src/component/rent/RentModalUserList.js, src/component/userManagement/UserBriefInfo.js
setHours(0,0,0,0) 을 사용해서 단순히 날짜만을 계산하도록 했습니다. 시간단위는 지워버리고 계산합니다.
=> JIP-337 FIX: penaltyEndDate 로직 수정

.github/workflows/main.yml, src/component/mypage/Mypage.js, src/component/rent/RentInquireBoxUser.js, src/component/rent/RentModalUserList.js, src/component/userManagement/UserBriefInfo.js
penaltyEndDate 로직을 수정하여 반영했습니다. 이제 Hours 를 지우고, 날짜 단위로만 비교연산을 합니다.
=> HOTFIX: penaltyEndDate 로직 수정

src/component/rent/RentInquireBoxUser.js, src/component/rent/RentModalUserList.js
=> HOTFIX: 페널티 엔드 데이트 수정

src/component/rent/RentInquireBoxUser.js, src/component/rent/RentModalUserList.js
203번 에러 메시지에 대한 수정을 진행했습니다. 이제 로그인에서 오류가 생기면, 모달에서 사서에게 문의해달라는 내용이 보입니다.
=> 203번 에러 메시지에 대한 수정을 진행했습니다.

src/css/RentBookWithBarcodeReader.css
QR코드로 대출할 때 모바일 환경에서는 css가 이상하게 보여 수정
=> JIP-347 FEAT: QR대출 모바일 환경 대응

src/data/error.js
42 인증 완료시 메세지 출력 할 수 있게 에러 메세지를 추가 했습니다.
- 이전
인증 완료시 메인 페이지로 이동되었습니다.
- 이후
마이 페이지에서 인증 완료 메세지가 출력 됩니다.
=> Jip 350 건의사항 62 번 인증하기 이후 팝업 띄우기

src/component/login/Register.js
- 개요
회원가입후에 바로 로그인 창으로 이동되어서, 제대로 회원가입이 된건지 모호한 상태였음.
회원가입 성공시 알림 메세지를 띄우게 하였음
- 이전
회원가입 성공시 로그인 창으로 이동되었음
- 이후
https://user-images.githubusercontent.com/48037775/180734016-55d5a266-9861-4493-b832-838149f3e6c5.mp4
=> JIP-349 CHORE: 회원가입 완료 알림 띄우기

.github/workflows/main.yml
github action 배포 실패로 변경사항을 되돌립니다
=> HOTFIX: deploy 변경사항 취소

src/component/book/BookDetail.js, src/component/book/BookStatus.js
1. 책 상세 페이지에서 책에 대한 정보가 잘못된 경우가 있어 수정 
2. 책 정보에 대한 보다 상세한 정보 추가
3. 예약 관련 로직 수정
https://github.com/jiphyeonjeon-42/backend/pull/172
=> JIP-356-책-상태-표시-fix

.github/workflows/main.yml
=> HOTFIX : GA ID 변경

src/component/main/MainNew.js
기존에 '신작'이라고 되어있던 문구를 '책들'로 바꾸었습니다.  새로 들어온게 무조건 신작은 아니여서!
=> JIP-362 CHORE: 신작 -> 책들

src/App.js
컴파일 오류 수정입니다
addbook 폴더 이동과정에서 놓쳤습니다
=> HOTFIX: App.js 경로 오류 수정

src/component/return/ReturnBook.js, src/component/return/ReturnBookWithBarcodeReader.js, src/css/ReturnBookWithReader.css
#258 
#https://github.com/jiphyeonjeon-42/backend/issues/195
- 반납할 책을 인식할 경우
- 반납할 수 없는 책을 인식할 경우
=> issue/255 add QR reader

src/App.js, src/LimitedRoute.js, src/component/utils/Header.js, src/component/utils/HeaderModal.js, src/data/headerMenu.js, src/utils/date.js
> 리팩토링의 오류를 수정하고 헤더 코드를 개선했습니다. 
- LimitedRoute에서 로그인 권한을 확인할 떄 전역상태 대신 로컬스토리지 참고
- App.js 코드 가독성 개선
- 헤더의 메뉴 구성 data/header.js 분리
- Header.js 코드 가독성 및 확장성 개선
- HeaderMobile.js 코드 가독성 및 확장성 개선
Resolves #275
=> REFACTOR: 로그인 정보 확인 경로 수정 및 헤더 리팩토링

src/api/books/useGetBooksInfoSearchUrl.js, src/component/search/Search.js
=> HOTFIX: 도서 검색 핫픽스 수정

public/robots.txt
=> FEAT: robots.txt

src/component/return/ReturnBookTable.js
* 연체 시, 굵은 빨간 글씨로 "연체 중"을 출력되도록 함.
테스트 화면
=> FIX: 반납 화면 대출 연체일을 연체 중으로 수정

src/api/auth/useGetAuthMe.js, src/atom/userState.js, src/component/mypage/EditEmailOrPassword.js
마이페이지 이메일/비밀번호 변경 페이지에서 불필요한 네트워크 요청 삭제 
- auth/me에서 받아오는 유저정보에 이메일 추가
- 마이페이지 이메일/비밀번호 변경 페이지에서 로컬스토리지에 저장된 이메일로 표기
변경사항 없음
Resolves #292
=> FIX: Issue/292 마이페이지 오류 수정

src/component/rent/RentInquireBoxUser.js
대출 페이지 반납예정일의 날짜 표기 오류를 수정했습니다 
> 불필요한 연산을 하는 displayDate 대신 dateFormat 함수로 변경
Resolves #295
=> FIX: 대출 페이지 반납예정일 날짜 표기 오류 수정

src/api/lendings/usePostLendingsMultiple.js, src/component/rent/RentModalBook.js, src/component/rent/RentModalBookList.js, src/component/rent/RentModalConfirm.js
- 대출이 잘못된 요청으로 진행되지 않는 오류를 해결했습니다. 
- GET books/search id -> bookId 변경에 따른 데이터 변형 반영
=> HOTFIX: 대출 잘못된 요청 오류 수정

src/api/books/useGetBooksSearch.js, src/api/lendings/usePostLendingsMultiple.js, src/component/rent/RentModalBook.js, src/component/rent/RentModalBookList.js, src/component/rent/RentModalConfirm.js
=> develop hotfix to main

package-lock.json, package.json, src/index.js
- 제보에 의한 디버깅만으로는 한계가 있음
- 오류에 대한 로그를 저장하고 , 주기적으로 확인할 수 있었으면
- 로그 수집 및 시각화 도구 제공
- 검색했을 때 참고자료가 많음
https://www.npmjs.com/package/@sentry/node
https://tech.kakaopay.com/post/frontend-sentry-monitoring/
https://engineering.linecorp.com/ko/blog/log-collection-system-sentry-on-premise/
https://teamdable.github.io/techblog/Sentry-Error-Tracking
https://docs.sentry.io/platforms/javascript/guides/react/configuration/integrations/react-router/
- 공식문서내 기본 설정까지 도입완료
- 에러바운더리 추가나 라우트 설정 등은 추후에 고려해볼 수 있을 듯 
기본 로그와의 차이점을 예상하기 어려움
=> Issue/294 sentry 도입

src/api/like/useDeleteLike.js, src/api/like/useGetLike.js, src/api/like/usePostLike.js
=> Issue/317/좋아요 요청 api hook

src/api/like/useDeleteLike.js, src/api/like/useGetLike.js, src/api/like/usePostLike.js
같은 bookInfoId로 요청이 갈 수 있도록 수정
#324
=> FIX: 같은 번호로 요청을 여러번 할 수 있게

src/index.js
- 센트리가 개발 환경에서 발생하는 오류 수집하지 않도록 수정합니다
- 센트리가 수집하는 환경을 인식할 수 있도록 enviroments 추가
- 별도의 env를 추가할 경우 CICD 작업이 필요하기 때문에 서버 api로 간단히 구분함
- 센트리 사이트의 환경에서 development 숨김처리 완료
https://docs.sentry.io/platforms/javascript/guides/electron/configuration/environments/
https://docs.sentry.io/product/sentry-basics/environments/#hidden-environments
Resolves #329
=> FIX: 센트리 개발 및 배포 환경 구분

src/component/return/ReturnBookFilter.js
=> FIX: 최신순 <-> 연체순

src/api/histories/useGetHistories.js, src/component/history/History.js, src/component/history/HistoryModalContents.js, src/component/history/HistoryTable.js, src/component/reservedloan/ReservedModalContents.js, src/css/HistoryModalContents.css, src/css/HistoryTable.css
#336 
- 1200px이하에서는 대출/반납 상세정보가 안보이게 수정(상세정보는 클릭시 보임)
- 클릭시 모달로 상세정보를 보여줌
=> 전체 대출/반납 기록 리팩토링

src/component/book/review/HandleReview.js, src/css/Tabs.css
* 상세페이지 리뷰 작성자만 수정하기 삭제하기 버튼 보이도록 수정
=> HOTFIX: 상세페이지 리뷰 작성자만 수정하기 삭제하기 버튼 보이도록 수정

src/css/BookManagementBooksListItem.css, src/css/BookManagementCart.css, src/css/ReviewManagementList.css
=> HOTFIX: 도서관리 css hotfix

src/component/book/BookDetail.js
분실도서의 경우 상태코드가 1임
현재코드에서는 분실도서가 있을 경우 예약이 불가능하기때문에 HOTFIX로 수정함
=> HOTFIX: 분실도서가 있을 경우 예약이 안 되는 버그 수정

src/component/history/History.js, src/component/history/HistoryFilter.js, src/css/HistoriesFilter.css
전체기록 필터 재선택시 해제되도록 수정했습니다
- 필터 클릭시 현재 선택된 필터 체크 
- 선택되어 있으면 해제되도록 수정
- 필터 간격 및 위치 조정
resolves #351
=> FIX: 전체기록 필터 선택된 상태면 해제되도록

index.html, src/component/eLibraryIn42Box/Box42CopyCat.jsx, src/css/Box42CopyCat.css
index html meta 태그 추가
배포버전 https://42library.kr 에서 전자도서관 GET 요청 실패
기타 제안받은 동작 수정
mixed content 문제 해결 https 에서 http 요청 허용 메타 추가
pin / quit 클릭시 alert 대신 다른 페이지(github)로 이동
[mixed content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content) 
[Upgrade-Insecure-Requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Upgrade-Insecure-Requests)
=> HOTFIX: mixed content 문제 해결 https 에서 http 요청 허용 메타 추가

index.html, src/component/eLibraryIn42Box/Box42CopyCat.jsx, src/css/Box42CopyCat.css
* HOTFIX: mixed content 문제 해결 https 에서 http 요청 허용 메타 추가
* HOTFIX: 만우절 페이지 pin box, quit box 동작 수정
=> develop to main

src/App.jsx
만우절 페이지 메인에 게시
- 복구를 대비해서 기존 라우팅 코드는 주석처리
- 메인페이지와 이벤트 페이지의 path 교환
=> CHORE: 메인 페이지와 이벤트 페이지 라우팅 변경

src/App.jsx
=> CHORE: 이벤트 종료로 메인페이지 정상화

src/env.d.ts, src/index.jsx
#408 
- env.d.ts에 속성 추가
- dsn 리터럴값 -> env으로 변경
다른 env 값과 일관성 유지하기 위해 REACT_APP_ prefix를 유지했습니다
=> refactor: sentry dsn값 env로 변경

.github/semantic.yml
모두가 일관적인 커밋 규칙을 따를 수 있도록 모든 커밋과 PR명이 [conventional commit 규칙](https://www.conventionalcommits.org/ko/v1.0.0/)을 따르는지 검사합니다.
참고: https://github.com/Ezard/semantic-prs#configuration
=> build: semantic.yml 추가

README.md
=> docs: CRA 로고를 vite로 변경

src/App.jsx, src/component/utils/Modal.tsx, src/component/utils/Tooltip.tsx, src/hook/useBound.ts
- feat #419 
- 기본적인 내용만 구현했습니다.
- 위치 지정 기능은 추후에 진행하면 좋을 것 같습니다.
```
import Tooltip from "component/utils/Tooltip";
<Tooltip description="추가하고자 하는 설명을 여기에 추가하면 됩니다">
<p>Hover</p>
</Tooltip>
```
=> feat: tooltip UI 위치 및 크기 확인 훅 구현 (#419)

README.md, package.json, pnpm-lock.yaml, src/component/utils/Button.stories.tsx, src/component/utils/Button.tsx, src/component/utils/Title.stories.tsx, src/component/utils/Title.tsx
- resolves #442
```sh
pnpm install
pnpm ladle serve
```
=> test: `Title`, `Button` 스토리 추가

src/component/rent/RentModalBook.tsx
- fixes #458 
- blocked by #476
이미 선택된 도서를 다시 인식하려는 경우 알림을 추가했습니다
수정사항 파악을 위해 branch 455와 비교하도록 설정해두었습니다
머지는 base 수정후 진행할 예정입니다.
=> fix: QR로 인식때 이미 선택된 책과 같은 도서인지 확인 로직 추가

src/component/rent/Rent.tsx, src/component/rent/RentModalBook.tsx, src/component/utils/BarcodeReader.tsx
- fixes #486
- 바코드리더 타입오류 
- ref 타입 element 명시
- 대출 선택된 도서 book id 대신 bookId
=> fix: 바코드 타입 오류 해결 및 Book id 타입 오류 해결

src/component/rent/RentModalBook.tsx, src/component/return/ReturnBook.tsx
QR 인식 관련 랜더링 오류 해결
- fixes #453
- 인식 성공시 언마운트되도록
- 반납 : 바코드리더 랜더링 조건을 false로 바꾸도록 함수 호출
- 대출 : 부모컴포넌트인 Modal이 계속 살아있어 조부모 상태변화로 재생성되면서 랜더링 조건이 true로 초기화됨-> 성공시 모달 닫도록 
- 랜더링 오류 및 네트워크 무한 요청 문제는 js/ts 변환과 다이얼로그 변경으로 해소되었음
=> fix: 대출/반납 qr 인식관련 랜더링오류

src/api/users/usePatchUsersUpdate.ts
Co-authored-by: KIM CHAN HEE <chanhihi@users.noreply.github.com>
Co-authored-by: sujikim <sujikim@student.42seoul.kr>
Co-authored-by: mink97 <mink97@users.noreply.github.com>
- fixes #
=> fix: user 업데이트시 즉시 수정 요청이 보내짐

src/asset/css/Tags.css, src/component/book/tag/TagList.tsx
https://github.com/jiphyeonjeon-42/frontend/assets/54838975/b9945a90-73bd-43ac-9169-3cb7d257e44b
- fixes #446
=> feat: 태그 상세 페이지 css 개선

.github/workflows/build.yml, .github/workflows/deploy-main.yml
1. develop-main 머지 컨플릭트를 수정했습니다.
2. 프로젝트 빌드가 잘 되는지 확인하는 간단한 워크플로우를 추가했습니다.
3. 배포 워크플로우 제목을 조금 더 명시적으로 수정했습니다.
=> ci: 빌드 가능 여부 테스트

.github/workflows/deploy-main.yml
- #514 재시도
- `workflow_dispatch`를 추가해서 수동 배포가 가능하게 변경
- pnpm 버전 명시
=> ci: pnpm 버전 명시

README.md
=> docs: :memo: README에 이름추가하기

src/asset/css/MainNew.css, src/asset/css/RentModalBookList.css, src/asset/css/RentModalUserList.css, src/asset/css/Tags.css
=> refactor: 쓰이지 않는 비표준 css 제거

src/asset/css/SearchBar.css, src/component/utils/SearchBar.tsx
=> refactor: 검색 바 아이콘 img로 변경

src/api/searchKeyword/useGetSearchKeyword.ts, src/asset/css/HeaderDefault.css, src/asset/css/HeaderMobile.css, src/asset/css/SearchRanking.css, src/component/utils/HeaderDefault.tsx, src/component/utils/HeaderMobile.tsx, src/component/utils/SearchRanking.tsx, src/component/utils/SearchRankingItem.tsx, src/component/utils/SearchRankingList.tsx, src/type/SearchKeyword.ts
- fixes #557 
|설명|이미지|
|---|---|
|인기검색어 등락|<img width="303" alt="image" src="https://github.com/jiphyeonjeon-42/frontend/assets/74622889/31a0463b-3e10-4264-bddf-c4add96c0913">|
|자동 애니메이션|![Sep-03-2023 14-33-43](https://github.com/jiphyeonjeon-42/frontend/assets/74622889/08d530a7-95c8-481c-b776-93c4bedcdee6)|
|어드민을 제외한 다른 페이지에서 모두 보임|![Sep-03-2023 14-39-20](https://github.com/jiphyeonjeon-42/frontend/assets/74622889/0a333f1f-ad13-449d-9611-676e479ff8cf)|
|반응형|![Sep-03-2023 14-38-16](https://github.com/jiphyeonjeon-42/frontend/assets/74622889/89c20d97-939d-4036-8da1-b6bb8b32b412)|
=> feat: 인기검색어 구현

src/api/cursus/useGetCursusRecommendBooks.ts, src/asset/css/BookSearchPreview.css, src/asset/css/MainNew.css, src/asset/css/MainRecommend.css, src/asset/css/Search.css, src/asset/css/SearchRanking.css, src/asset/css/SubTitle.css, src/component/main/MainRecommend.tsx, src/component/main/MainRecommendList.tsx, src/component/main/MainRecommendTitle.tsx, src/component/utils/BookSearchPreview.tsx, src/component/utils/BookSearchPreviewList.tsx, src/component/utils/CarouselRoot.tsx, src/component/utils/HeaderMobile.tsx, src/component/utils/Paginations.tsx, src/component/utils/SearchRankingItem.tsx, src/component/utils/SearchRankingList.tsx
- fixes #567 
https://42born2code.slack.com/archives/C05LG4481PU/p1693800824239209
=> fix: 검색개선 UI 피드백 반영

src/api/books/useGetBooksInfoSearchUrl.ts, src/api/books/usePatchBooksUpdate.ts, src/component/bookManagement/BookManagementModalDetail.tsx, src/component/main/MainRecommendList.tsx, src/component/utils/BookSearchBar.tsx, src/component/utils/BookSearchPreview.tsx, src/component/utils/BookSearchPreviewList.tsx, src/component/utils/CarouselRoot.tsx, src/component/utils/SearchBarDropDown.tsx
경진대회 기간동안 피드백을 반영했습니다
- fixes #569
=> fix: 검색 개선 UI 피드백 2차

src/component/search/Category.tsx, src/component/search/CategoryFilter.tsx, src/component/search/Search.tsx
1. 변수명 변경 "userCate" 같은 모호한 표현 대신 selectedCategory 등으로 명시
2. DOM 접근방식 개선 querySelector -> useRef
3. 복잡한 for문의 합계 대신 array filter 및 getBoundingClientRect를 활용
- getBoundingClientRect :  뷰포트기준 해당 엘리먼트의 위치와 크기 정보 확인하는 메서드
https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect
- resolves #471
=> refactor: search/CategoryFilter 가독성 개선

vite.config.ts
=> build: base 추가

src/component/information/Information.jsx
/information에 나와있는 집현전 위치 정보를 업데이트 합니다.
- fixes #612
=> chore: 인포메이션 집현전 위치 업데이트

vite.config.ts
[hotfix: info/* 로 직접접근하면 깨지는 버그 핫픽스](https://github.com/jiphyeonjeon-42/frontend/commit/0a630858ffe457b8655ca22eddd40ee5f12b8f36)
=> fix: `info/*` 로 직접접근하면 깨지는 버그 핫픽스

vite.config.ts
https://github.com/jiphyeonjeon-42/frontend/pull/603 에서 추가한 이후로 info/{id} 경로 서빙되지 않음
=> fix: base `./` 제거

src/component/return/ReturnModalContents.tsx
- fixes #645 
추후 구조 개선을 통해 api 호출을 명확히 알 수 있도록 수정
=> fix: 반납시 condition이 안 들어가는 버그

src/component/return/ReturnModalContents.tsx, vite.config.ts
반납이 안 되는 버그 hotfix
https://github.com/jiphyeonjeon-42/frontend/pull/646
=> hotfix: 반납이 안 되는 버그

README.md
=> docs: README 팀원 추가
